/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountWithdrawal
 */
export interface AccountWithdrawal {
    /**
     * Amount of the withdrawal.
     * @type {number}
     * @memberof AccountWithdrawal
     */
    amount: number;
}

/**
 * Check if a given object implements the AccountWithdrawal interface.
 */
export function instanceOfAccountWithdrawal(value: object): value is AccountWithdrawal {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function AccountWithdrawalFromJSON(json: any): AccountWithdrawal {
    return AccountWithdrawalFromJSONTyped(json, false);
}

export function AccountWithdrawalFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountWithdrawal {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
    };
}

export function AccountWithdrawalToJSON(value?: AccountWithdrawal | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
    };
}

