/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MobileAccount } from './MobileAccount';
import {
    MobileAccountFromJSON,
    MobileAccountFromJSONTyped,
    MobileAccountToJSON,
} from './MobileAccount';

/**
 * 
 * @export
 * @interface AccountVerify
 */
export interface AccountVerify {
    /**
     * 
     * @type {Array<MobileAccount>}
     * @memberof AccountVerify
     */
    accounts: Array<MobileAccount>;
}

/**
 * Check if a given object implements the AccountVerify interface.
 */
export function instanceOfAccountVerify(value: object): value is AccountVerify {
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    return true;
}

export function AccountVerifyFromJSON(json: any): AccountVerify {
    return AccountVerifyFromJSONTyped(json, false);
}

export function AccountVerifyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountVerify {
    if (json == null) {
        return json;
    }
    return {
        
        'accounts': ((json['accounts'] as Array<any>).map(MobileAccountFromJSON)),
    };
}

export function AccountVerifyToJSON(value?: AccountVerify | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accounts': ((value['accounts'] as Array<any>).map(MobileAccountToJSON)),
    };
}

