/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedAccountStop
 */
export interface PatchedAccountStop {
    /**
     * The account's unique ID on the core.
     * @type {string}
     * @memberof PatchedAccountStop
     */
    readonly accountId?: string;
    /**
     * The lower bound check number which the stop applies to or the check number when targeting a single check with a specified amount.
     * @type {string}
     * @memberof PatchedAccountStop
     */
    minCheckNumber?: string;
    /**
     * The upper bound check number which the stop applies to.
     * @type {string}
     * @memberof PatchedAccountStop
     */
    maxCheckNumber?: string;
    /**
     * The amount of the original payment that should be targeted for the stop.
     * @type {number}
     * @memberof PatchedAccountStop
     */
    amount?: number;
}

/**
 * Check if a given object implements the PatchedAccountStop interface.
 */
export function instanceOfPatchedAccountStop(value: object): value is PatchedAccountStop {
    return true;
}

export function PatchedAccountStopFromJSON(json: any): PatchedAccountStop {
    return PatchedAccountStopFromJSONTyped(json, false);
}

export function PatchedAccountStopFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedAccountStop {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'minCheckNumber': json['min_check_number'] == null ? undefined : json['min_check_number'],
        'maxCheckNumber': json['max_check_number'] == null ? undefined : json['max_check_number'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function PatchedAccountStopToJSON(value?: Omit<PatchedAccountStop, 'account_id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'min_check_number': value['minCheckNumber'],
        'max_check_number': value['maxCheckNumber'],
        'amount': value['amount'],
    };
}

