/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const State432Enum = {
    Processed: 'processed',
    Canceled: 'canceled',
    Pending: 'pending',
    Returned: 'returned'
} as const;
export type State432Enum = typeof State432Enum[keyof typeof State432Enum];


export function instanceOfState432Enum(value: any): boolean {
    for (const key in State432Enum) {
        if (Object.prototype.hasOwnProperty.call(State432Enum, key)) {
            if ((State432Enum as Record<string, State432Enum>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function State432EnumFromJSON(json: any): State432Enum {
    return State432EnumFromJSONTyped(json, false);
}

export function State432EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): State432Enum {
    return json as State432Enum;
}

export function State432EnumToJSON(value?: State432Enum | null): any {
    return value as any;
}

