/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.8.181)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UserAccessibilityPreferences,
  UserAccessibilityPreferencesRequest,
} from '../models/index';
import {
    UserAccessibilityPreferencesFromJSON,
    UserAccessibilityPreferencesToJSON,
    UserAccessibilityPreferencesRequestFromJSON,
    UserAccessibilityPreferencesRequestToJSON,
} from '../models/index';

export interface MeAccessibilityPreferencesUpdateRequest {
    userAccessibilityPreferencesRequest?: UserAccessibilityPreferencesRequest;
}

/**
 * 
 */
export class AccessibilityApi extends runtime.BaseAPI {

    /**
     * Returns the authenticated user\'s accessibility preferences. When no preferences have been set, defaults are returned without persisting a row.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Get user accessibility preferences
     */
    async meAccessibilityPreferencesRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserAccessibilityPreferences>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read"]);
        }

        const response = await this.request({
            path: `/v1/me/accessibility_preferences/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserAccessibilityPreferencesFromJSON(jsonValue));
    }

    /**
     * Returns the authenticated user\'s accessibility preferences. When no preferences have been set, defaults are returned without persisting a row.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Get user accessibility preferences
     */
    async meAccessibilityPreferencesRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserAccessibilityPreferences> {
        const response = await this.meAccessibilityPreferencesRetrieveRaw(initOverrides);
        return await response.value();
    }

    /**
     * Idempotent upsert of the authenticated user\'s accessibility preferences. Creates the resource on first write and fully replaces it on subsequent writes.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Set user accessibility preferences
     */
    async meAccessibilityPreferencesUpdateRaw(requestParameters: MeAccessibilityPreferencesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserAccessibilityPreferences>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/me/accessibility_preferences/`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserAccessibilityPreferencesRequestToJSON(requestParameters['userAccessibilityPreferencesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserAccessibilityPreferencesFromJSON(jsonValue));
    }

    /**
     * Idempotent upsert of the authenticated user\'s accessibility preferences. Creates the resource on first write and fully replaces it on subsequent writes.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Set user accessibility preferences
     */
    async meAccessibilityPreferencesUpdate(requestParameters: MeAccessibilityPreferencesUpdateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserAccessibilityPreferences> {
        const response = await this.meAccessibilityPreferencesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
