/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.4.349)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountsDocumentsRetrieve404Response,
  AchTransactionRequest,
  AchTransfersCreate422Response,
  NotFoundError,
  PaginatedAchTransactionList,
  RetrieveAchTransaction,
} from '../models/index';
import {
    AccountsDocumentsRetrieve404ResponseFromJSON,
    AccountsDocumentsRetrieve404ResponseToJSON,
    AchTransactionRequestFromJSON,
    AchTransactionRequestToJSON,
    AchTransfersCreate422ResponseFromJSON,
    AchTransfersCreate422ResponseToJSON,
    NotFoundErrorFromJSON,
    NotFoundErrorToJSON,
    PaginatedAchTransactionListFromJSON,
    PaginatedAchTransactionListToJSON,
    RetrieveAchTransactionFromJSON,
    RetrieveAchTransactionToJSON,
} from '../models/index';

export interface AchTransfersCreateRequest {
    achTransactionRequest: AchTransactionRequest;
}

export interface AchTransfersListRequest {
    filter?: AchTransfersListFilterEnum;
    page?: number;
    perPage?: number;
}

/**
 * 
 */
export class AchTransfersApi extends runtime.BaseAPI {

    /**
     * Transfer funds between two accounts. The target accounts should be either an account at the financial institution belonging to the user or a verified external account.  A list of eligible accounts can be retrieved or listed from the accounts endpoints.  If the `instant` flag is provided for a push external transfer, processing will be done via FedNow and core posting will be immediate, otherwise all external transfers are processed via ACH by default.  Additionally, this endpoint requires the use of sudo elevation. For details, please refer to the <a href=\"#/operations/retrieve_sudo\">sudo documentation.</a>    All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create an ACH transfer
     */
    async achTransfersCreateRaw(requestParameters: AchTransfersCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RetrieveAchTransaction>> {
        if (requestParameters['achTransactionRequest'] == null) {
            throw new runtime.RequiredError(
                'achTransactionRequest',
                'Required parameter "achTransactionRequest" was null or undefined when calling achTransfersCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/v1/transfers/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AchTransactionRequestToJSON(requestParameters['achTransactionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RetrieveAchTransactionFromJSON(jsonValue));
    }

    /**
     * Transfer funds between two accounts. The target accounts should be either an account at the financial institution belonging to the user or a verified external account.  A list of eligible accounts can be retrieved or listed from the accounts endpoints.  If the `instant` flag is provided for a push external transfer, processing will be done via FedNow and core posting will be immediate, otherwise all external transfers are processed via ACH by default.  Additionally, this endpoint requires the use of sudo elevation. For details, please refer to the <a href=\"#/operations/retrieve_sudo\">sudo documentation.</a>    All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create an ACH transfer
     */
    async achTransfersCreate(requestParameters: AchTransfersCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RetrieveAchTransaction> {
        const response = await this.achTransfersCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List the authenticated user\'s ACH transfers. Transfers are movements of funds between two internal accounts or two verified external accounts.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List ACH transfers
     */
    async achTransfersListRaw(requestParameters: AchTransfersListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedAchTransactionList>> {
        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/v1/transfers/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedAchTransactionListFromJSON(jsonValue));
    }

    /**
     * List the authenticated user\'s ACH transfers. Transfers are movements of funds between two internal accounts or two verified external accounts.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List ACH transfers
     */
    async achTransfersList(requestParameters: AchTransfersListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedAchTransactionList> {
        const response = await this.achTransfersListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AchTransfersListFilterEnum = {
    Recent: 'recent'
} as const;
export type AchTransfersListFilterEnum = typeof AchTransfersListFilterEnum[keyof typeof AchTransfersListFilterEnum];
