/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2025.5.148)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountAlertRule,
  AccountAlertRuleRequest,
  AccountsDocumentsRetrieve404Response,
  AchDetailsCreate400Response,
  LoanAlertRule,
  LoanAlertRuleRequest,
  PaginatedAccountAlertRuleList,
  PaginatedLoanAlertRuleList,
  PaginatedTransactionAlertRuleList,
  TransactionAlertRule,
  TransactionAlertRuleRequest,
} from '../models/index';
import {
    AccountAlertRuleFromJSON,
    AccountAlertRuleToJSON,
    AccountAlertRuleRequestFromJSON,
    AccountAlertRuleRequestToJSON,
    AccountsDocumentsRetrieve404ResponseFromJSON,
    AccountsDocumentsRetrieve404ResponseToJSON,
    AchDetailsCreate400ResponseFromJSON,
    AchDetailsCreate400ResponseToJSON,
    LoanAlertRuleFromJSON,
    LoanAlertRuleToJSON,
    LoanAlertRuleRequestFromJSON,
    LoanAlertRuleRequestToJSON,
    PaginatedAccountAlertRuleListFromJSON,
    PaginatedAccountAlertRuleListToJSON,
    PaginatedLoanAlertRuleListFromJSON,
    PaginatedLoanAlertRuleListToJSON,
    PaginatedTransactionAlertRuleListFromJSON,
    PaginatedTransactionAlertRuleListToJSON,
    TransactionAlertRuleFromJSON,
    TransactionAlertRuleToJSON,
    TransactionAlertRuleRequestFromJSON,
    TransactionAlertRuleRequestToJSON,
} from '../models/index';

export interface AccountAlertCreateRequest {
    accountAlertRuleRequest: AccountAlertRuleRequest;
}

export interface AccountAlertDeleteRequest {
    uuid: string;
}

export interface AccountAlertListRequest {
    page?: number;
}

export interface AccountAlertRetrieveRequest {
    uuid: string;
}

export interface AccountAlertUpdateRequest {
    uuid: string;
    accountAlertRuleRequest: AccountAlertRuleRequest;
}

export interface LoanAlertCreateRequest {
    loanAlertRuleRequest: LoanAlertRuleRequest;
}

export interface LoanAlertDeleteRequest {
    uuid: string;
}

export interface LoanAlertListRequest {
    page?: number;
}

export interface LoanAlertRetrieveRequest {
    uuid: string;
}

export interface LoanAlertUpdateRequest {
    uuid: string;
    loanAlertRuleRequest: LoanAlertRuleRequest;
}

export interface TransactionAlertCreateRequest {
    transactionAlertRuleRequest: TransactionAlertRuleRequest;
}

export interface TransactionAlertDeleteRequest {
    uuid: string;
}

export interface TransactionAlertListRequest {
    page?: number;
}

export interface TransactionAlertRetrieveRequest {
    uuid: string;
}

export interface TransactionAlertUpdateRequest {
    uuid: string;
    transactionAlertRuleRequest: TransactionAlertRuleRequest;
}

/**
 * 
 */
export class AlertsApi extends runtime.BaseAPI {

    /**
     * Activates an account alert for the user. The `alert_key` field determines which alert to activate for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create an account alert
     */
    async accountAlertCreateRaw(requestParameters: AccountAlertCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountAlertRule>> {
        if (requestParameters['accountAlertRuleRequest'] == null) {
            throw new runtime.RequiredError(
                'accountAlertRuleRequest',
                'Required parameter "accountAlertRuleRequest" was null or undefined when calling accountAlertCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/account/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountAlertRuleRequestToJSON(requestParameters['accountAlertRuleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountAlertRuleFromJSON(jsonValue));
    }

    /**
     * Activates an account alert for the user. The `alert_key` field determines which alert to activate for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create an account alert
     */
    async accountAlertCreate(requestParameters: AccountAlertCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountAlertRule> {
        const response = await this.accountAlertCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deactivates an account alert for the user. The `alert_key` field determines which alert to deactivate for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Delete an account alert
     */
    async accountAlertDeleteRaw(requestParameters: AccountAlertDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling accountAlertDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/account/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deactivates an account alert for the user. The `alert_key` field determines which alert to deactivate for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Delete an account alert
     */
    async accountAlertDelete(requestParameters: AccountAlertDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.accountAlertDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * List all active account alerts for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List account alerts
     */
    async accountAlertListRaw(requestParameters: AccountAlertListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedAccountAlertRuleList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/account/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedAccountAlertRuleListFromJSON(jsonValue));
    }

    /**
     * List all active account alerts for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List account alerts
     */
    async accountAlertList(requestParameters: AccountAlertListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedAccountAlertRuleList> {
        const response = await this.accountAlertListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves an account alert for the user    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Retrieve an account alert
     */
    async accountAlertRetrieveRaw(requestParameters: AccountAlertRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountAlertRule>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling accountAlertRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/account/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountAlertRuleFromJSON(jsonValue));
    }

    /**
     * Retrieves an account alert for the user    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Retrieve an account alert
     */
    async accountAlertRetrieve(requestParameters: AccountAlertRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountAlertRule> {
        const response = await this.accountAlertRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an account alert\'s metadata for the user    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Update an account alert
     */
    async accountAlertUpdateRaw(requestParameters: AccountAlertUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountAlertRule>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling accountAlertUpdate().'
            );
        }

        if (requestParameters['accountAlertRuleRequest'] == null) {
            throw new runtime.RequiredError(
                'accountAlertRuleRequest',
                'Required parameter "accountAlertRuleRequest" was null or undefined when calling accountAlertUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/account/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AccountAlertRuleRequestToJSON(requestParameters['accountAlertRuleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountAlertRuleFromJSON(jsonValue));
    }

    /**
     * Updates an account alert\'s metadata for the user    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Update an account alert
     */
    async accountAlertUpdate(requestParameters: AccountAlertUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountAlertRule> {
        const response = await this.accountAlertUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Activates a loan alert for the user. The `alert_key` field determines which alert to activate for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create a loan alert
     */
    async loanAlertCreateRaw(requestParameters: LoanAlertCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoanAlertRule>> {
        if (requestParameters['loanAlertRuleRequest'] == null) {
            throw new runtime.RequiredError(
                'loanAlertRuleRequest',
                'Required parameter "loanAlertRuleRequest" was null or undefined when calling loanAlertCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/loan/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoanAlertRuleRequestToJSON(requestParameters['loanAlertRuleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoanAlertRuleFromJSON(jsonValue));
    }

    /**
     * Activates a loan alert for the user. The `alert_key` field determines which alert to activate for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create a loan alert
     */
    async loanAlertCreate(requestParameters: LoanAlertCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoanAlertRule> {
        const response = await this.loanAlertCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deactivates a loan alert for the user. The `alert_key` field determines which alert to deactivate for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Delete a loan alert
     */
    async loanAlertDeleteRaw(requestParameters: LoanAlertDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling loanAlertDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/loan/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deactivates a loan alert for the user. The `alert_key` field determines which alert to deactivate for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Delete a loan alert
     */
    async loanAlertDelete(requestParameters: LoanAlertDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.loanAlertDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * List all active loan alerts for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List loan alerts
     */
    async loanAlertListRaw(requestParameters: LoanAlertListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedLoanAlertRuleList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/loan/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedLoanAlertRuleListFromJSON(jsonValue));
    }

    /**
     * List all active loan alerts for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List loan alerts
     */
    async loanAlertList(requestParameters: LoanAlertListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedLoanAlertRuleList> {
        const response = await this.loanAlertListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a loan alert for the user    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Retrieve a loan alert
     */
    async loanAlertRetrieveRaw(requestParameters: LoanAlertRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoanAlertRule>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling loanAlertRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/loan/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoanAlertRuleFromJSON(jsonValue));
    }

    /**
     * Retrieves a loan alert for the user    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Retrieve a loan alert
     */
    async loanAlertRetrieve(requestParameters: LoanAlertRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoanAlertRule> {
        const response = await this.loanAlertRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a loan alert\'s metadata for the user    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Update a loan alert
     */
    async loanAlertUpdateRaw(requestParameters: LoanAlertUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoanAlertRule>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling loanAlertUpdate().'
            );
        }

        if (requestParameters['loanAlertRuleRequest'] == null) {
            throw new runtime.RequiredError(
                'loanAlertRuleRequest',
                'Required parameter "loanAlertRuleRequest" was null or undefined when calling loanAlertUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/loan/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LoanAlertRuleRequestToJSON(requestParameters['loanAlertRuleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoanAlertRuleFromJSON(jsonValue));
    }

    /**
     * Updates a loan alert\'s metadata for the user    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Update a loan alert
     */
    async loanAlertUpdate(requestParameters: LoanAlertUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoanAlertRule> {
        const response = await this.loanAlertUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Activates a transaction alert for the user. The `alert_key` determines which alert to activate for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create a transaction alert
     */
    async transactionAlertCreateRaw(requestParameters: TransactionAlertCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionAlertRule>> {
        if (requestParameters['transactionAlertRuleRequest'] == null) {
            throw new runtime.RequiredError(
                'transactionAlertRuleRequest',
                'Required parameter "transactionAlertRuleRequest" was null or undefined when calling transactionAlertCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/transaction/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionAlertRuleRequestToJSON(requestParameters['transactionAlertRuleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionAlertRuleFromJSON(jsonValue));
    }

    /**
     * Activates a transaction alert for the user. The `alert_key` determines which alert to activate for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create a transaction alert
     */
    async transactionAlertCreate(requestParameters: TransactionAlertCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionAlertRule> {
        const response = await this.transactionAlertCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deactivates a transaction alert for the user. The `alert_key` determines which alert to deactivate for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Delete a transaction alert
     */
    async transactionAlertDeleteRaw(requestParameters: TransactionAlertDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling transactionAlertDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/transaction/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deactivates a transaction alert for the user. The `alert_key` determines which alert to deactivate for the user.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Delete a transaction alert
     */
    async transactionAlertDelete(requestParameters: TransactionAlertDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transactionAlertDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * List all active transaction alerts for the user.     <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List transaction alerts
     */
    async transactionAlertListRaw(requestParameters: TransactionAlertListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedTransactionAlertRuleList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/transaction/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedTransactionAlertRuleListFromJSON(jsonValue));
    }

    /**
     * List all active transaction alerts for the user.     <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List transaction alerts
     */
    async transactionAlertList(requestParameters: TransactionAlertListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedTransactionAlertRuleList> {
        const response = await this.transactionAlertListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a transaction alert for the user    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Retrieve a transaction alert
     */
    async transactionAlertRetrieveRaw(requestParameters: TransactionAlertRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionAlertRule>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling transactionAlertRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/transaction/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionAlertRuleFromJSON(jsonValue));
    }

    /**
     * Retrieves a transaction alert for the user    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Retrieve a transaction alert
     */
    async transactionAlertRetrieve(requestParameters: TransactionAlertRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionAlertRule> {
        const response = await this.transactionAlertRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a transaction alert\'s metadata for the user    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Update a transaction alert
     */
    async transactionAlertUpdateRaw(requestParameters: TransactionAlertUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionAlertRule>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling transactionAlertUpdate().'
            );
        }

        if (requestParameters['transactionAlertRuleRequest'] == null) {
            throw new runtime.RequiredError(
                'transactionAlertRuleRequest',
                'Required parameter "transactionAlertRuleRequest" was null or undefined when calling transactionAlertUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alerts/transaction/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionAlertRuleRequestToJSON(requestParameters['transactionAlertRuleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionAlertRuleFromJSON(jsonValue));
    }

    /**
     * Updates a transaction alert\'s metadata for the user    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Update a transaction alert
     */
    async transactionAlertUpdate(requestParameters: TransactionAlertUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionAlertRule> {
        const response = await this.transactionAlertUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
