/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.7.0)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BulkPayment,
  BulkPaymentFromTemplateRequest,
  BulkPaymentRequest,
  GeneralError,
  NotFoundError,
  PaginatedBulkPaymentList,
  PermissionDeniedError,
} from '../models/index';
import {
    BulkPaymentFromJSON,
    BulkPaymentToJSON,
    BulkPaymentFromTemplateRequestFromJSON,
    BulkPaymentFromTemplateRequestToJSON,
    BulkPaymentRequestFromJSON,
    BulkPaymentRequestToJSON,
    GeneralErrorFromJSON,
    GeneralErrorToJSON,
    NotFoundErrorFromJSON,
    NotFoundErrorToJSON,
    PaginatedBulkPaymentListFromJSON,
    PaginatedBulkPaymentListToJSON,
    PermissionDeniedErrorFromJSON,
    PermissionDeniedErrorToJSON,
} from '../models/index';

export interface BulkPaymentsCancelUpdateRequest {
    uuid: string;
}

export interface BulkPaymentsCreateRequest {
    bulkPaymentRequest: BulkPaymentRequest;
}

export interface BulkPaymentsListRequest {
    limit?: number;
    offset?: number;
    ordering?: string;
    search?: string;
}

export interface BulkPaymentsRetrieveRequest {
    uuid: string;
}

export interface BulkPaymentsTemplatesCreateRequest {
    bulkPaymentFromTemplateRequest: BulkPaymentFromTemplateRequest;
}

/**
 * 
 */
export class BulkPaymentsApi extends runtime.BaseAPI {

    /**
     * Cancel an existing bulk payment.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Cancel a bulk payment
     */
    async bulkPaymentsCancelUpdateRaw(requestParameters: BulkPaymentsCancelUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkPayment>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling bulkPaymentsCancelUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/bulk_payments/{uuid}/cancel/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkPaymentFromJSON(jsonValue));
    }

    /**
     * Cancel an existing bulk payment.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Cancel a bulk payment
     */
    async bulkPaymentsCancelUpdate(requestParameters: BulkPaymentsCancelUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkPayment> {
        const response = await this.bulkPaymentsCancelUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new bulk payment.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create a bulk payment
     */
    async bulkPaymentsCreateRaw(requestParameters: BulkPaymentsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkPayment>> {
        if (requestParameters['bulkPaymentRequest'] == null) {
            throw new runtime.RequiredError(
                'bulkPaymentRequest',
                'Required parameter "bulkPaymentRequest" was null or undefined when calling bulkPaymentsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/bulk_payments/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkPaymentRequestToJSON(requestParameters['bulkPaymentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkPaymentFromJSON(jsonValue));
    }

    /**
     * Create a new bulk payment.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create a bulk payment
     */
    async bulkPaymentsCreate(requestParameters: BulkPaymentsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkPayment> {
        const response = await this.bulkPaymentsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all bulk payments for the authenticated user.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List bulk payments
     */
    async bulkPaymentsListRaw(requestParameters: BulkPaymentsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedBulkPaymentList>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['ordering'] != null) {
            queryParameters['ordering'] = requestParameters['ordering'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read"]);
        }

        const response = await this.request({
            path: `/v1/bulk_payments/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedBulkPaymentListFromJSON(jsonValue));
    }

    /**
     * List all bulk payments for the authenticated user.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List bulk payments
     */
    async bulkPaymentsList(requestParameters: BulkPaymentsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedBulkPaymentList> {
        const response = await this.bulkPaymentsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a single bulk payment by its ID.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Retrieve a bulk payment
     */
    async bulkPaymentsRetrieveRaw(requestParameters: BulkPaymentsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkPayment>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling bulkPaymentsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read"]);
        }

        const response = await this.request({
            path: `/v1/bulk_payments/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkPaymentFromJSON(jsonValue));
    }

    /**
     * Retrieve a single bulk payment by its ID.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Retrieve a bulk payment
     */
    async bulkPaymentsRetrieve(requestParameters: BulkPaymentsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkPayment> {
        const response = await this.bulkPaymentsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new bulk payment from an existing bulk payment template. The template\'s active version provides the originating account, transaction details, and recipient rows; the request supplies the title, active version ID for staleness detection, and any per-payment overrides.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create a bulk payment from a template
     */
    async bulkPaymentsTemplatesCreateRaw(requestParameters: BulkPaymentsTemplatesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkPayment>> {
        if (requestParameters['bulkPaymentFromTemplateRequest'] == null) {
            throw new runtime.RequiredError(
                'bulkPaymentFromTemplateRequest',
                'Required parameter "bulkPaymentFromTemplateRequest" was null or undefined when calling bulkPaymentsTemplatesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/bulk_payments/templates/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkPaymentFromTemplateRequestToJSON(requestParameters['bulkPaymentFromTemplateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkPaymentFromJSON(jsonValue));
    }

    /**
     * Create a new bulk payment from an existing bulk payment template. The template\'s active version provides the originating account, transaction details, and recipient rows; the request supplies the title, active version ID for staleness detection, and any per-payment overrides.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create a bulk payment from a template
     */
    async bulkPaymentsTemplatesCreate(requestParameters: BulkPaymentsTemplatesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkPayment> {
        const response = await this.bulkPaymentsTemplatesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
