/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AutomaticSavingsEnrollmentRetrieve422Response,
  CardsList403Response,
  CreateEnrollmentUrlsResponse,
  EnrollCreate400Response,
  Enrollment,
  EnrollmentUrlCreate,
  GenericError,
  NotFoundError,
  UsersEnrollmentCodeCreate200Response,
  VerifyEnrollment,
} from '../models/index';
import {
    AutomaticSavingsEnrollmentRetrieve422ResponseFromJSON,
    AutomaticSavingsEnrollmentRetrieve422ResponseToJSON,
    CardsList403ResponseFromJSON,
    CardsList403ResponseToJSON,
    CreateEnrollmentUrlsResponseFromJSON,
    CreateEnrollmentUrlsResponseToJSON,
    EnrollCreate400ResponseFromJSON,
    EnrollCreate400ResponseToJSON,
    EnrollmentFromJSON,
    EnrollmentToJSON,
    EnrollmentUrlCreateFromJSON,
    EnrollmentUrlCreateToJSON,
    GenericErrorFromJSON,
    GenericErrorToJSON,
    NotFoundErrorFromJSON,
    NotFoundErrorToJSON,
    UsersEnrollmentCodeCreate200ResponseFromJSON,
    UsersEnrollmentCodeCreate200ResponseToJSON,
    VerifyEnrollmentFromJSON,
    VerifyEnrollmentToJSON,
} from '../models/index';

export interface EnrollCreateRequest {
    format?: EnrollCreateFormatEnum;
    enrollment?: Omit<Enrollment, 'user'|'devices'>;
}

export interface EnrollVerifyCreateRequest {
    verifyEnrollment: Omit<VerifyEnrollment, 'user'>;
    format?: EnrollVerifyCreateFormatEnum;
}

export interface EnrollmentsCreateRequest {
    format?: EnrollmentsCreateFormatEnum;
    enrollmentUrlCreate?: EnrollmentUrlCreate;
}

export interface UsersEnrollmentCodeCreateRequest {
    userUuid: string;
    format?: UsersEnrollmentCodeCreateFormatEnum;
}

export interface UsersEnrollmentCompleteCreateRequest {
    userUuid: string;
    format?: UsersEnrollmentCompleteCreateFormatEnum;
}

/**
 * 
 */
export class EnrollmentsApi extends runtime.BaseAPI {

    /**
     * Verifies a user\'s details against the core and creates a digital banking user.
     * Create a digital banking user
     */
    async enrollCreateRaw(requestParameters: EnrollCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Enrollment>> {
        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/v1/enroll/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EnrollmentToJSON(requestParameters['enrollment']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnrollmentFromJSON(jsonValue));
    }

    /**
     * Verifies a user\'s details against the core and creates a digital banking user.
     * Create a digital banking user
     */
    async enrollCreate(requestParameters: EnrollCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Enrollment> {
        const response = await this.enrollCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verifies an enrolling user\'s enrollment code. If verified, returns user information.
     * Verify enrollment code
     */
    async enrollVerifyCreateRaw(requestParameters: EnrollVerifyCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyEnrollment>> {
        if (requestParameters['verifyEnrollment'] == null) {
            throw new runtime.RequiredError(
                'verifyEnrollment',
                'Required parameter "verifyEnrollment" was null or undefined when calling enrollVerifyCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/v1/enroll_verify/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyEnrollmentToJSON(requestParameters['verifyEnrollment']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyEnrollmentFromJSON(jsonValue));
    }

    /**
     * Verifies an enrolling user\'s enrollment code. If verified, returns user information.
     * Verify enrollment code
     */
    async enrollVerifyCreate(requestParameters: EnrollVerifyCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyEnrollment> {
        const response = await this.enrollVerifyCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a URL that enables a user to enroll without entering their details on the first step of enrollment. Verifies a user\'s information on the core and generates a link that allows the user to automatically proceed past the initial step of enrollment. After clicking the link, and depending on configuration, the user is redirected to the enrollment code verification or username/password step of enrollment.
     * Create enrollment URL
     */
    async enrollmentsCreateRaw(requestParameters: EnrollmentsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateEnrollmentUrlsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/enrollments`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EnrollmentUrlCreateToJSON(requestParameters['enrollmentUrlCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateEnrollmentUrlsResponseFromJSON(jsonValue));
    }

    /**
     * Returns a URL that enables a user to enroll without entering their details on the first step of enrollment. Verifies a user\'s information on the core and generates a link that allows the user to automatically proceed past the initial step of enrollment. After clicking the link, and depending on configuration, the user is redirected to the enrollment code verification or username/password step of enrollment.
     * Create enrollment URL
     */
    async enrollmentsCreate(requestParameters: EnrollmentsCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateEnrollmentUrlsResponse> {
        const response = await this.enrollmentsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Regenerates an enrollment code for an enrolling user and resends the enrollment code email.
     * Create a new enrollment code
     */
    async usersEnrollmentCodeCreateRaw(requestParameters: UsersEnrollmentCodeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersEnrollmentCodeCreate200Response>> {
        if (requestParameters['userUuid'] == null) {
            throw new runtime.RequiredError(
                'userUuid',
                'Required parameter "userUuid" was null or undefined when calling usersEnrollmentCodeCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/v1/users/{user_uuid}/enrollment_code/`.replace(`{${"user_uuid"}}`, encodeURIComponent(String(requestParameters['userUuid']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersEnrollmentCodeCreate200ResponseFromJSON(jsonValue));
    }

    /**
     * Regenerates an enrollment code for an enrolling user and resends the enrollment code email.
     * Create a new enrollment code
     */
    async usersEnrollmentCodeCreate(requestParameters: UsersEnrollmentCodeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersEnrollmentCodeCreate200Response> {
        const response = await this.usersEnrollmentCodeCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Validates that the user meets the requirements to complete enrollment, which may include that they have a permitted MFA device and that they have correctly assented to their estatement preferences. If they meet these requirements, they\'ll be registered in our system as having completed enrollment.
     * Set user as enrolled
     */
    async usersEnrollmentCompleteCreateRaw(requestParameters: UsersEnrollmentCompleteCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userUuid'] == null) {
            throw new runtime.RequiredError(
                'userUuid',
                'Required parameter "userUuid" was null or undefined when calling usersEnrollmentCompleteCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/users/{user_uuid}/enrollment_complete`.replace(`{${"user_uuid"}}`, encodeURIComponent(String(requestParameters['userUuid']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Validates that the user meets the requirements to complete enrollment, which may include that they have a permitted MFA device and that they have correctly assented to their estatement preferences. If they meet these requirements, they\'ll be registered in our system as having completed enrollment.
     * Set user as enrolled
     */
    async usersEnrollmentCompleteCreate(requestParameters: UsersEnrollmentCompleteCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersEnrollmentCompleteCreateRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const EnrollCreateFormatEnum = {
    Html: 'html',
    Json: 'json'
} as const;
export type EnrollCreateFormatEnum = typeof EnrollCreateFormatEnum[keyof typeof EnrollCreateFormatEnum];
/**
 * @export
 */
export const EnrollVerifyCreateFormatEnum = {
    Html: 'html',
    Json: 'json'
} as const;
export type EnrollVerifyCreateFormatEnum = typeof EnrollVerifyCreateFormatEnum[keyof typeof EnrollVerifyCreateFormatEnum];
/**
 * @export
 */
export const EnrollmentsCreateFormatEnum = {
    Html: 'html',
    Json: 'json'
} as const;
export type EnrollmentsCreateFormatEnum = typeof EnrollmentsCreateFormatEnum[keyof typeof EnrollmentsCreateFormatEnum];
/**
 * @export
 */
export const UsersEnrollmentCodeCreateFormatEnum = {
    Html: 'html',
    Json: 'json'
} as const;
export type UsersEnrollmentCodeCreateFormatEnum = typeof UsersEnrollmentCodeCreateFormatEnum[keyof typeof UsersEnrollmentCodeCreateFormatEnum];
/**
 * @export
 */
export const UsersEnrollmentCompleteCreateFormatEnum = {
    Html: 'html',
    Json: 'json'
} as const;
export type UsersEnrollmentCompleteCreateFormatEnum = typeof UsersEnrollmentCompleteCreateFormatEnum[keyof typeof UsersEnrollmentCompleteCreateFormatEnum];
