/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2025.11.321)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateAnswerRequest,
  Impression,
  ImpressionRequest,
  PaginatedImpressionList,
  Survey,
} from '../models/index';
import {
    CreateAnswerRequestFromJSON,
    CreateAnswerRequestToJSON,
    ImpressionFromJSON,
    ImpressionToJSON,
    ImpressionRequestFromJSON,
    ImpressionRequestToJSON,
    PaginatedImpressionListFromJSON,
    PaginatedImpressionListToJSON,
    SurveyFromJSON,
    SurveyToJSON,
} from '../models/index';

export interface SurveyImpressionsCreateRequest {
    impressionRequest: ImpressionRequest;
}

export interface SurveyImpressionsCreateAnswerCreateRequest {
    createAnswerRequest: CreateAnswerRequest;
}

export interface SurveyImpressionsListRequest {
    uuid: string;
    page?: number;
}

/**
 * 
 */
export class SurveysApi extends runtime.BaseAPI {

    /**
     * All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     */
    async surveyImpressionsCreateRaw(requestParameters: SurveyImpressionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Impression>> {
        if (requestParameters['impressionRequest'] == null) {
            throw new runtime.RequiredError(
                'impressionRequest',
                'Required parameter "impressionRequest" was null or undefined when calling surveyImpressionsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/survey_impressions/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImpressionRequestToJSON(requestParameters['impressionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImpressionFromJSON(jsonValue));
    }

    /**
     * All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     */
    async surveyImpressionsCreate(requestParameters: SurveyImpressionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Impression> {
        const response = await this.surveyImpressionsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     */
    async surveyImpressionsCreateAnswerCreateRaw(requestParameters: SurveyImpressionsCreateAnswerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createAnswerRequest'] == null) {
            throw new runtime.RequiredError(
                'createAnswerRequest',
                'Required parameter "createAnswerRequest" was null or undefined when calling surveyImpressionsCreateAnswerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/survey_impressions/create_answer/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAnswerRequestToJSON(requestParameters['createAnswerRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     */
    async surveyImpressionsCreateAnswerCreate(requestParameters: SurveyImpressionsCreateAnswerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.surveyImpressionsCreateAnswerCreateRaw(requestParameters, initOverrides);
    }

    /**
     * All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     */
    async surveyImpressionsListRaw(requestParameters: SurveyImpressionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedImpressionList>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling surveyImpressionsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['uuid'] != null) {
            queryParameters['uuid'] = requestParameters['uuid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/survey_impressions/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedImpressionListFromJSON(jsonValue));
    }

    /**
     * All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     */
    async surveyImpressionsList(requestParameters: SurveyImpressionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedImpressionList> {
        const response = await this.surveyImpressionsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the current survey that should be displayed to the authenticated user. Only one survey is shown at a time, prioritized by creation date (newest first).   Surveys are filtered based on: - User\'s response history and survey frequency settings (once, monthly, quarterly, yearly) - Survey status (active, not archived, not draft) - Survey date range (starts_at and ends_at) - Product type (banking vs command/staff)  Returns empty JSON `{}` if no survey should be shown to the user.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Get current survey
     */
    async surveysRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Survey>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("OAuth2", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/surveys/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SurveyFromJSON(jsonValue));
    }

    /**
     * Returns the current survey that should be displayed to the authenticated user. Only one survey is shown at a time, prioritized by creation date (newest first).   Surveys are filtered based on: - User\'s response history and survey frequency settings (once, monthly, quarterly, yearly) - Survey status (active, not archived, not draft) - Survey date range (starts_at and ends_at) - Product type (banking vs command/staff)  Returns empty JSON `{}` if no survey should be shown to the user.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Get current survey
     */
    async surveysRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Survey> {
        const response = await this.surveysRetrieveRaw(initOverrides);
        return await response.value();
    }

}
