/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.6.565)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GeneralError,
  NotFoundError,
  PaginatedSwiftWireTemplateList,
  PatchedSwiftWireTemplateRequest,
  SwiftWireTemplate,
  SwiftWireTemplateRequest,
} from '../models/index';
import {
    GeneralErrorFromJSON,
    GeneralErrorToJSON,
    NotFoundErrorFromJSON,
    NotFoundErrorToJSON,
    PaginatedSwiftWireTemplateListFromJSON,
    PaginatedSwiftWireTemplateListToJSON,
    PatchedSwiftWireTemplateRequestFromJSON,
    PatchedSwiftWireTemplateRequestToJSON,
    SwiftWireTemplateFromJSON,
    SwiftWireTemplateToJSON,
    SwiftWireTemplateRequestFromJSON,
    SwiftWireTemplateRequestToJSON,
} from '../models/index';

export interface SwiftwireTemplatesCreateRequest {
    swiftWireTemplateRequest: SwiftWireTemplateRequest;
}

export interface SwiftwireTemplatesDestroyRequest {
    uuid: string;
}

export interface SwiftwireTemplatesListRequest {
    page?: number;
}

export interface SwiftwireTemplatesPartialUpdateRequest {
    uuid: string;
    patchedSwiftWireTemplateRequest?: PatchedSwiftWireTemplateRequest;
}

export interface SwiftwireTemplatesRetrieveRequest {
    uuid: string;
}

export interface SwiftwireTemplatesUpdateRequest {
    uuid: string;
    swiftWireTemplateRequest: SwiftWireTemplateRequest;
}

/**
 * 
 */
export class SwiftWireTemplatesApi extends runtime.BaseAPI {

    /**
     * Create a template that can be used to send Swift Wire transfers.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create a Swift Wire template
     */
    async swiftwireTemplatesCreateRaw(requestParameters: SwiftwireTemplatesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SwiftWireTemplate>> {
        if (requestParameters['swiftWireTemplateRequest'] == null) {
            throw new runtime.RequiredError(
                'swiftWireTemplateRequest',
                'Required parameter "swiftWireTemplateRequest" was null or undefined when calling swiftwireTemplatesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/swiftwire_templates/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SwiftWireTemplateRequestToJSON(requestParameters['swiftWireTemplateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SwiftWireTemplateFromJSON(jsonValue));
    }

    /**
     * Create a template that can be used to send Swift Wire transfers.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create a Swift Wire template
     */
    async swiftwireTemplatesCreate(requestParameters: SwiftwireTemplatesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SwiftWireTemplate> {
        const response = await this.swiftwireTemplatesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a specified Swift Wire template belonging to the user. The template will continue to exist in the database, but won\'t be retrievable by the user. The name of the deleted template will be available for use in creating a new template.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Delete a Swift Wire template
     */
    async swiftwireTemplatesDestroyRaw(requestParameters: SwiftwireTemplatesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling swiftwireTemplatesDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/swiftwire_templates/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a specified Swift Wire template belonging to the user. The template will continue to exist in the database, but won\'t be retrievable by the user. The name of the deleted template will be available for use in creating a new template.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Delete a Swift Wire template
     */
    async swiftwireTemplatesDestroy(requestParameters: SwiftwireTemplatesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.swiftwireTemplatesDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * List a user\'s Swift Wire templates for their organization.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List Swift Wire templates
     */
    async swiftwireTemplatesListRaw(requestParameters: SwiftwireTemplatesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedSwiftWireTemplateList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read"]);
        }

        const response = await this.request({
            path: `/v1/swiftwire_templates/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedSwiftWireTemplateListFromJSON(jsonValue));
    }

    /**
     * List a user\'s Swift Wire templates for their organization.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List Swift Wire templates
     */
    async swiftwireTemplatesList(requestParameters: SwiftwireTemplatesListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedSwiftWireTemplateList> {
        const response = await this.swiftwireTemplatesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the details of a template belonging to authenticated user, identified by `uuid`  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Update a Swift Wire template
     */
    async swiftwireTemplatesPartialUpdateRaw(requestParameters: SwiftwireTemplatesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SwiftWireTemplate>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling swiftwireTemplatesPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/swiftwire_templates/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedSwiftWireTemplateRequestToJSON(requestParameters['patchedSwiftWireTemplateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SwiftWireTemplateFromJSON(jsonValue));
    }

    /**
     * Update the details of a template belonging to authenticated user, identified by `uuid`  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Update a Swift Wire template
     */
    async swiftwireTemplatesPartialUpdate(requestParameters: SwiftwireTemplatesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SwiftWireTemplate> {
        const response = await this.swiftwireTemplatesPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch details for a specified template.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Retrieve a Swift Wire template
     */
    async swiftwireTemplatesRetrieveRaw(requestParameters: SwiftwireTemplatesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SwiftWireTemplate>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling swiftwireTemplatesRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read"]);
        }

        const response = await this.request({
            path: `/v1/swiftwire_templates/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SwiftWireTemplateFromJSON(jsonValue));
    }

    /**
     * Fetch details for a specified template.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Retrieve a Swift Wire template
     */
    async swiftwireTemplatesRetrieve(requestParameters: SwiftwireTemplatesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SwiftWireTemplate> {
        const response = await this.swiftwireTemplatesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the details of a template belonging to authenticated user, identified by `uuid`  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Update a Swift Wire template
     */
    async swiftwireTemplatesUpdateRaw(requestParameters: SwiftwireTemplatesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SwiftWireTemplate>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling swiftwireTemplatesUpdate().'
            );
        }

        if (requestParameters['swiftWireTemplateRequest'] == null) {
            throw new runtime.RequiredError(
                'swiftWireTemplateRequest',
                'Required parameter "swiftWireTemplateRequest" was null or undefined when calling swiftwireTemplatesUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/swiftwire_templates/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SwiftWireTemplateRequestToJSON(requestParameters['swiftWireTemplateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SwiftWireTemplateFromJSON(jsonValue));
    }

    /**
     * Update the details of a template belonging to authenticated user, identified by `uuid`  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Update a Swift Wire template
     */
    async swiftwireTemplatesUpdate(requestParameters: SwiftwireTemplatesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SwiftWireTemplate> {
        const response = await this.swiftwireTemplatesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
