/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.6.264)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedWireCSVFieldMappingList,
  PatchedWireCSVFieldMappingRequest,
  WireCSVFieldMapping,
  WireCSVFieldMappingRequest,
  WireImportBatchResponse,
  WireImportCSVImport,
  WireImportCSVImportResponse,
  WireImportCSVParseRequest,
  WireImportCSVParseResponse,
  WireImportSubmitRequest,
} from '../models/index';
import {
    PaginatedWireCSVFieldMappingListFromJSON,
    PaginatedWireCSVFieldMappingListToJSON,
    PatchedWireCSVFieldMappingRequestFromJSON,
    PatchedWireCSVFieldMappingRequestToJSON,
    WireCSVFieldMappingFromJSON,
    WireCSVFieldMappingToJSON,
    WireCSVFieldMappingRequestFromJSON,
    WireCSVFieldMappingRequestToJSON,
    WireImportBatchResponseFromJSON,
    WireImportBatchResponseToJSON,
    WireImportCSVImportFromJSON,
    WireImportCSVImportToJSON,
    WireImportCSVImportResponseFromJSON,
    WireImportCSVImportResponseToJSON,
    WireImportCSVParseRequestFromJSON,
    WireImportCSVParseRequestToJSON,
    WireImportCSVParseResponseFromJSON,
    WireImportCSVParseResponseToJSON,
    WireImportSubmitRequestFromJSON,
    WireImportSubmitRequestToJSON,
} from '../models/index';

export interface WireImportCsvDownloadRetrieveRequest {
    fileName: string;
}

export interface WireImportCsvImportCreateRequest {
    file: Blob;
    hasHeaderRow?: boolean;
}

export interface WireImportCsvMappingsCreateRequest {
    wireCSVFieldMappingRequest: WireCSVFieldMappingRequest;
}

export interface WireImportCsvMappingsDestroyRequest {
    uuid: string;
}

export interface WireImportCsvMappingsListRequest {
    page?: number;
}

export interface WireImportCsvMappingsPartialUpdateRequest {
    uuid: string;
    patchedWireCSVFieldMappingRequest?: PatchedWireCSVFieldMappingRequest;
}

export interface WireImportCsvMappingsUpdateRequest {
    uuid: string;
    wireCSVFieldMappingRequest: WireCSVFieldMappingRequest;
}

export interface WireImportCsvParseCreateRequest {
    wireImportCSVParseRequest: WireImportCSVParseRequest;
}

export interface WireImportCsvSubmitCreateRequest {
    wireImportSubmitRequest: WireImportSubmitRequest;
}

/**
 * 
 */
export class WireImportApi extends runtime.BaseAPI {

    /**
     * All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     */
    async wireImportCsvDownloadRetrieveRaw(requestParameters: WireImportCsvDownloadRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WireImportCSVImport>> {
        if (requestParameters['fileName'] == null) {
            throw new runtime.RequiredError(
                'fileName',
                'Required parameter "fileName" was null or undefined when calling wireImportCsvDownloadRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read"]);
        }

        const response = await this.request({
            path: `/v1/wire_import/csv/download/{file_name}/`.replace(`{${"file_name"}}`, encodeURIComponent(String(requestParameters['fileName']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WireImportCSVImportFromJSON(jsonValue));
    }

    /**
     * All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     */
    async wireImportCsvDownloadRetrieve(requestParameters: WireImportCsvDownloadRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WireImportCSVImport> {
        const response = await this.wireImportCsvDownloadRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload a CSV file, store it in S3, and return preview rows with a suggested column mapping.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Import wire CSV
     */
    async wireImportCsvImportCreateRaw(requestParameters: WireImportCsvImportCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WireImportCSVImportResponse>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling wireImportCsvImportCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['hasHeaderRow'] != null) {
            formParams.append('has_header_row', requestParameters['hasHeaderRow'] as any);
        }

        const response = await this.request({
            path: `/v1/wire_import/csv/import/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WireImportCSVImportResponseFromJSON(jsonValue));
    }

    /**
     * Upload a CSV file, store it in S3, and return preview rows with a suggested column mapping.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Import wire CSV
     */
    async wireImportCsvImportCreate(requestParameters: WireImportCsvImportCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WireImportCSVImportResponse> {
        const response = await this.wireImportCsvImportCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Save a new named wire CSV field mapping for the authenticated user\'s organization.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create a saved wire CSV mapping
     */
    async wireImportCsvMappingsCreateRaw(requestParameters: WireImportCsvMappingsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WireCSVFieldMapping>> {
        if (requestParameters['wireCSVFieldMappingRequest'] == null) {
            throw new runtime.RequiredError(
                'wireCSVFieldMappingRequest',
                'Required parameter "wireCSVFieldMappingRequest" was null or undefined when calling wireImportCsvMappingsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/wire_import/csv/mappings/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WireCSVFieldMappingRequestToJSON(requestParameters['wireCSVFieldMappingRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WireCSVFieldMappingFromJSON(jsonValue));
    }

    /**
     * Save a new named wire CSV field mapping for the authenticated user\'s organization.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Create a saved wire CSV mapping
     */
    async wireImportCsvMappingsCreate(requestParameters: WireImportCsvMappingsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WireCSVFieldMapping> {
        const response = await this.wireImportCsvMappingsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a saved wire CSV field mapping by UUID.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Delete a saved wire CSV mapping
     */
    async wireImportCsvMappingsDestroyRaw(requestParameters: WireImportCsvMappingsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling wireImportCsvMappingsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/wire_import/csv/mappings/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a saved wire CSV field mapping by UUID.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Delete a saved wire CSV mapping
     */
    async wireImportCsvMappingsDestroy(requestParameters: WireImportCsvMappingsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.wireImportCsvMappingsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Return all saved wire CSV field mappings for the authenticated user\'s organization.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List saved wire CSV mappings
     */
    async wireImportCsvMappingsListRaw(requestParameters: WireImportCsvMappingsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedWireCSVFieldMappingList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read"]);
        }

        const response = await this.request({
            path: `/v1/wire_import/csv/mappings/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedWireCSVFieldMappingListFromJSON(jsonValue));
    }

    /**
     * Return all saved wire CSV field mappings for the authenticated user\'s organization.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * List saved wire CSV mappings
     */
    async wireImportCsvMappingsList(requestParameters: WireImportCsvMappingsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedWireCSVFieldMappingList> {
        const response = await this.wireImportCsvMappingsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     */
    async wireImportCsvMappingsPartialUpdateRaw(requestParameters: WireImportCsvMappingsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WireCSVFieldMapping>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling wireImportCsvMappingsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/wire_import/csv/mappings/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedWireCSVFieldMappingRequestToJSON(requestParameters['patchedWireCSVFieldMappingRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WireCSVFieldMappingFromJSON(jsonValue));
    }

    /**
     * All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     */
    async wireImportCsvMappingsPartialUpdate(requestParameters: WireImportCsvMappingsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WireCSVFieldMapping> {
        const response = await this.wireImportCsvMappingsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a saved wire CSV field mapping by UUID.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Update a saved wire CSV mapping
     */
    async wireImportCsvMappingsUpdateRaw(requestParameters: WireImportCsvMappingsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WireCSVFieldMapping>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling wireImportCsvMappingsUpdate().'
            );
        }

        if (requestParameters['wireCSVFieldMappingRequest'] == null) {
            throw new runtime.RequiredError(
                'wireCSVFieldMappingRequest',
                'Required parameter "wireCSVFieldMappingRequest" was null or undefined when calling wireImportCsvMappingsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/wire_import/csv/mappings/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WireCSVFieldMappingRequestToJSON(requestParameters['wireCSVFieldMappingRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WireCSVFieldMappingFromJSON(jsonValue));
    }

    /**
     * Update a saved wire CSV field mapping by UUID.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Update a saved wire CSV mapping
     */
    async wireImportCsvMappingsUpdate(requestParameters: WireImportCsvMappingsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WireCSVFieldMapping> {
        const response = await this.wireImportCsvMappingsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Apply column mappings to the uploaded CSV, validate fields, match recipients, and return parsed rows.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Parse wire CSV
     */
    async wireImportCsvParseCreateRaw(requestParameters: WireImportCsvParseCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WireImportCSVParseResponse>> {
        if (requestParameters['wireImportCSVParseRequest'] == null) {
            throw new runtime.RequiredError(
                'wireImportCSVParseRequest',
                'Required parameter "wireImportCSVParseRequest" was null or undefined when calling wireImportCsvParseCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/wire_import/csv/parse/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WireImportCSVParseRequestToJSON(requestParameters['wireImportCSVParseRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WireImportCSVParseResponseFromJSON(jsonValue));
    }

    /**
     * Apply column mappings to the uploaded CSV, validate fields, match recipients, and return parsed rows.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Parse wire CSV
     */
    async wireImportCsvParseCreate(requestParameters: WireImportCsvParseCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WireImportCSVParseResponse> {
        const response = await this.wireImportCsvParseCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a WireImportBatch and individual WireTransactions from validated rows.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Submit wire import batch
     */
    async wireImportCsvSubmitCreateRaw(requestParameters: WireImportCsvSubmitCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WireImportBatchResponse>> {
        if (requestParameters['wireImportSubmitRequest'] == null) {
            throw new runtime.RequiredError(
                'wireImportSubmitRequest',
                'Required parameter "wireImportSubmitRequest" was null or undefined when calling wireImportCsvSubmitCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["write"]);
        }

        const response = await this.request({
            path: `/v1/wire_import/csv/submit/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WireImportSubmitRequestToJSON(requestParameters['wireImportSubmitRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WireImportBatchResponseFromJSON(jsonValue));
    }

    /**
     * Create a WireImportBatch and individual WireTransactions from validated rows.  All monetary values are represented in minor units, or the smallest unit of the currency with no decimal (e.g., cents). For example, $10.00 is represented as 1000.    <i>How can we improve these docs?             <a href=\"mailto:docs+feedback@narmi.com\">Share your feedback.</a></i>
     * Submit wire import batch
     */
    async wireImportCsvSubmitCreate(requestParameters: WireImportCsvSubmitCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WireImportBatchResponse> {
        const response = await this.wireImportCsvSubmitCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
