/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.6.456)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ACHImportCSVParsedRow } from './ACHImportCSVParsedRow';
import {
    ACHImportCSVParsedRowFromJSON,
    ACHImportCSVParsedRowFromJSONTyped,
    ACHImportCSVParsedRowToJSON,
} from './ACHImportCSVParsedRow';

/**
 * 
 * @export
 * @interface ACHImportCSVParseResponse
 */
export interface ACHImportCSVParseResponse {
    /**
     * 
     * @type {string}
     * @memberof ACHImportCSVParseResponse
     */
    s3Key: string;
    /**
     * 
     * @type {string}
     * @memberof ACHImportCSVParseResponse
     */
    organizationFileUuid: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ACHImportCSVParseResponse
     */
    thresholdWarningFields?: Array<string>;
    /**
     * 
     * @type {Array<ACHImportCSVParsedRow>}
     * @memberof ACHImportCSVParseResponse
     */
    rows: Array<ACHImportCSVParsedRow>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ACHImportCSVParseResponse
     */
    warnings?: Array<string>;
    /**
     * 
     * @type {any}
     * @memberof ACHImportCSVParseResponse
     */
    warningContext?: any | null;
}

/**
 * Check if a given object implements the ACHImportCSVParseResponse interface.
 */
export function instanceOfACHImportCSVParseResponse(value: object): value is ACHImportCSVParseResponse {
    if (!('s3Key' in value) || value['s3Key'] === undefined) return false;
    if (!('organizationFileUuid' in value) || value['organizationFileUuid'] === undefined) return false;
    if (!('rows' in value) || value['rows'] === undefined) return false;
    return true;
}

export function ACHImportCSVParseResponseFromJSON(json: any): ACHImportCSVParseResponse {
    return ACHImportCSVParseResponseFromJSONTyped(json, false);
}

export function ACHImportCSVParseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ACHImportCSVParseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        's3Key': json['s3_key'],
        'organizationFileUuid': json['organization_file_uuid'],
        'thresholdWarningFields': json['threshold_warning_fields'] == null ? undefined : json['threshold_warning_fields'],
        'rows': ((json['rows'] as Array<any>).map(ACHImportCSVParsedRowFromJSON)),
        'warnings': json['warnings'] == null ? undefined : json['warnings'],
        'warningContext': json['warning_context'] == null ? undefined : json['warning_context'],
    };
}

export function ACHImportCSVParseResponseToJSON(value?: ACHImportCSVParseResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        's3_key': value['s3Key'],
        'organization_file_uuid': value['organizationFileUuid'],
        'threshold_warning_fields': value['thresholdWarningFields'],
        'rows': ((value['rows'] as Array<any>).map(ACHImportCSVParsedRowToJSON)),
        'warnings': value['warnings'],
        'warning_context': value['warningContext'],
    };
}

