/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.4.198)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ACHImportNACHAPaymentRow } from './ACHImportNACHAPaymentRow';
import {
    ACHImportNACHAPaymentRowFromJSON,
    ACHImportNACHAPaymentRowFromJSONTyped,
    ACHImportNACHAPaymentRowToJSON,
} from './ACHImportNACHAPaymentRow';

/**
 * 
 * @export
 * @interface ACHImportNACHAUploadResponse
 */
export interface ACHImportNACHAUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof ACHImportNACHAUploadResponse
     */
    s3Key: string;
    /**
     * 
     * @type {string}
     * @memberof ACHImportNACHAUploadResponse
     */
    organizationFileUuid: string;
    /**
     * 
     * @type {string}
     * @memberof ACHImportNACHAUploadResponse
     */
    sourceAccount: string;
    /**
     * 
     * @type {string}
     * @memberof ACHImportNACHAUploadResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ACHImportNACHAUploadResponse
     */
    internalNote: string;
    /**
     * 
     * @type {Array<ACHImportNACHAPaymentRow>}
     * @memberof ACHImportNACHAUploadResponse
     */
    rows: Array<ACHImportNACHAPaymentRow>;
}

/**
 * Check if a given object implements the ACHImportNACHAUploadResponse interface.
 */
export function instanceOfACHImportNACHAUploadResponse(value: object): value is ACHImportNACHAUploadResponse {
    if (!('s3Key' in value) || value['s3Key'] === undefined) return false;
    if (!('organizationFileUuid' in value) || value['organizationFileUuid'] === undefined) return false;
    if (!('sourceAccount' in value) || value['sourceAccount'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('internalNote' in value) || value['internalNote'] === undefined) return false;
    if (!('rows' in value) || value['rows'] === undefined) return false;
    return true;
}

export function ACHImportNACHAUploadResponseFromJSON(json: any): ACHImportNACHAUploadResponse {
    return ACHImportNACHAUploadResponseFromJSONTyped(json, false);
}

export function ACHImportNACHAUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ACHImportNACHAUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        's3Key': json['s3_key'],
        'organizationFileUuid': json['organization_file_uuid'],
        'sourceAccount': json['source_account'],
        'title': json['title'],
        'internalNote': json['internal_note'],
        'rows': ((json['rows'] as Array<any>).map(ACHImportNACHAPaymentRowFromJSON)),
    };
}

export function ACHImportNACHAUploadResponseToJSON(value?: ACHImportNACHAUploadResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        's3_key': value['s3Key'],
        'organization_file_uuid': value['organizationFileUuid'],
        'source_account': value['sourceAccount'],
        'title': value['title'],
        'internal_note': value['internalNote'],
        'rows': ((value['rows'] as Array<any>).map(ACHImportNACHAPaymentRowToJSON)),
    };
}

