/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2025.5.26)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankingAccessTokenCreate
 */
export interface BankingAccessTokenCreate {
    /**
     * 
     * @type {string}
     * @memberof BankingAccessTokenCreate
     */
    nickname: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BankingAccessTokenCreate
     */
    ipAllowlist: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BankingAccessTokenCreate
     */
    readonly uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof BankingAccessTokenCreate
     */
    readonly user?: string;
    /**
     * 
     * @type {string}
     * @memberof BankingAccessTokenCreate
     */
    readonly username?: string;
    /**
     * 
     * @type {Date}
     * @memberof BankingAccessTokenCreate
     */
    readonly created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BankingAccessTokenCreate
     */
    readonly lastUsed?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BankingAccessTokenCreate
     */
    readonly expires?: Date;
    /**
     * 
     * @type {string}
     * @memberof BankingAccessTokenCreate
     */
    readonly token?: string;
    /**
     * 
     * @type {string}
     * @memberof BankingAccessTokenCreate
     */
    readonly secret?: string;
}

/**
 * Check if a given object implements the BankingAccessTokenCreate interface.
 */
export function instanceOfBankingAccessTokenCreate(value: object): value is BankingAccessTokenCreate {
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('ipAllowlist' in value) || value['ipAllowlist'] === undefined) return false;
    return true;
}

export function BankingAccessTokenCreateFromJSON(json: any): BankingAccessTokenCreate {
    return BankingAccessTokenCreateFromJSONTyped(json, false);
}

export function BankingAccessTokenCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankingAccessTokenCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'],
        'ipAllowlist': json['ip_allowlist'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'user': json['user'] == null ? undefined : json['user'],
        'username': json['username'] == null ? undefined : json['username'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'lastUsed': json['last_used'] == null ? undefined : (new Date(json['last_used'])),
        'expires': json['expires'] == null ? undefined : (new Date(json['expires'])),
        'token': json['token'] == null ? undefined : json['token'],
        'secret': json['secret'] == null ? undefined : json['secret'],
    };
}

export function BankingAccessTokenCreateToJSON(value?: Omit<BankingAccessTokenCreate, 'uuid'|'user'|'username'|'created'|'last_used'|'expires'|'token'|'secret'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nickname': value['nickname'],
        'ip_allowlist': value['ipAllowlist'],
    };
}

