/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2025.8.298)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BlankEnum = {
    Empty: ''
} as const;
export type BlankEnum = typeof BlankEnum[keyof typeof BlankEnum];


export function instanceOfBlankEnum(value: any): boolean {
    for (const key in BlankEnum) {
        if (Object.prototype.hasOwnProperty.call(BlankEnum, key)) {
            if ((BlankEnum as Record<string, BlankEnum>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BlankEnumFromJSON(json: any): BlankEnum {
    return BlankEnumFromJSONTyped(json, false);
}

export function BlankEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlankEnum {
    return json as BlankEnum;
}

export function BlankEnumToJSON(value?: BlankEnum | null): any {
    return value as any;
}

