/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.8.311)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExpediteChoiceEnum } from './ExpediteChoiceEnum';
import {
    ExpediteChoiceEnumFromJSON,
    ExpediteChoiceEnumFromJSONTyped,
    ExpediteChoiceEnumToJSON,
} from './ExpediteChoiceEnum';
import type { TransactionTypeEnum } from './TransactionTypeEnum';
import {
    TransactionTypeEnumFromJSON,
    TransactionTypeEnumFromJSONTyped,
    TransactionTypeEnumToJSON,
} from './TransactionTypeEnum';

/**
 * 
 * @export
 * @interface BulkPaymentPaymentInputRequest
 */
export interface BulkPaymentPaymentInputRequest {
    /**
     * A field that represents the stringified UUID of a related object.
     * @type {string}
     * @memberof BulkPaymentPaymentInputRequest
     */
    recipient: string;
    /**
     * This value is expressed as an integer in the currency's smallest unit (e.g. cents), not as a decimal. For example, $5.00 is represented as 500 and $0.99 as 99.
     * @type {number}
     * @memberof BulkPaymentPaymentInputRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof BulkPaymentPaymentInputRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkPaymentPaymentInputRequest
     */
    recurringRule?: string | null;
    /**
     * 
     * @type {TransactionTypeEnum}
     * @memberof BulkPaymentPaymentInputRequest
     */
    transactionType?: TransactionTypeEnum;
    /**
     * 
     * @type {ExpediteChoiceEnum}
     * @memberof BulkPaymentPaymentInputRequest
     */
    expediteChoice?: ExpediteChoiceEnum;
}

/**
 * Check if a given object implements the BulkPaymentPaymentInputRequest interface.
 */
export function instanceOfBulkPaymentPaymentInputRequest(value: object): value is BulkPaymentPaymentInputRequest {
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function BulkPaymentPaymentInputRequestFromJSON(json: any): BulkPaymentPaymentInputRequest {
    return BulkPaymentPaymentInputRequestFromJSONTyped(json, false);
}

export function BulkPaymentPaymentInputRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkPaymentPaymentInputRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recipient': json['recipient'],
        'amount': json['amount'],
        'description': json['description'] == null ? undefined : json['description'],
        'recurringRule': json['recurring_rule'] == null ? undefined : json['recurring_rule'],
        'transactionType': json['transaction_type'] == null ? undefined : TransactionTypeEnumFromJSON(json['transaction_type']),
        'expediteChoice': json['expedite_choice'] == null ? undefined : ExpediteChoiceEnumFromJSON(json['expedite_choice']),
    };
}

export function BulkPaymentPaymentInputRequestToJSON(value?: BulkPaymentPaymentInputRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'recipient': value['recipient'],
        'amount': value['amount'],
        'description': value['description'],
        'recurring_rule': value['recurringRule'],
        'transaction_type': TransactionTypeEnumToJSON(value['transactionType']),
        'expedite_choice': ExpediteChoiceEnumToJSON(value['expediteChoice']),
    };
}

