/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.8.179)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CSVFieldMapping
 */
export interface CSVFieldMapping {
    /**
     * 
     * @type {string}
     * @memberof CSVFieldMapping
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CSVFieldMapping
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CSVFieldMapping
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CSVFieldMapping
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof CSVFieldMapping
     */
    hasHeaderRow?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CSVFieldMapping
     */
    dateColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CSVFieldMapping
     */
    dateColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CSVFieldMapping
     */
    recipientNameColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CSVFieldMapping
     */
    recipientNameColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CSVFieldMapping
     */
    routingNumberColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CSVFieldMapping
     */
    routingNumberColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CSVFieldMapping
     */
    accountNumberColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CSVFieldMapping
     */
    accountNumberColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CSVFieldMapping
     */
    accountTypeColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CSVFieldMapping
     */
    accountTypeColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CSVFieldMapping
     */
    actionColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CSVFieldMapping
     */
    actionColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CSVFieldMapping
     */
    descriptionColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CSVFieldMapping
     */
    descriptionColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CSVFieldMapping
     */
    amountColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CSVFieldMapping
     */
    amountColumnHeader?: string | null;
}

/**
 * Check if a given object implements the CSVFieldMapping interface.
 */
export function instanceOfCSVFieldMapping(value: object): value is CSVFieldMapping {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CSVFieldMappingFromJSON(json: any): CSVFieldMapping {
    return CSVFieldMappingFromJSONTyped(json, false);
}

export function CSVFieldMappingFromJSONTyped(json: any, ignoreDiscriminator: boolean): CSVFieldMapping {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'name': json['name'],
        'hasHeaderRow': json['has_header_row'] == null ? undefined : json['has_header_row'],
        'dateColumnIndex': json['date_column_index'] == null ? undefined : json['date_column_index'],
        'dateColumnHeader': json['date_column_header'] == null ? undefined : json['date_column_header'],
        'recipientNameColumnIndex': json['recipient_name_column_index'] == null ? undefined : json['recipient_name_column_index'],
        'recipientNameColumnHeader': json['recipient_name_column_header'] == null ? undefined : json['recipient_name_column_header'],
        'routingNumberColumnIndex': json['routing_number_column_index'] == null ? undefined : json['routing_number_column_index'],
        'routingNumberColumnHeader': json['routing_number_column_header'] == null ? undefined : json['routing_number_column_header'],
        'accountNumberColumnIndex': json['account_number_column_index'] == null ? undefined : json['account_number_column_index'],
        'accountNumberColumnHeader': json['account_number_column_header'] == null ? undefined : json['account_number_column_header'],
        'accountTypeColumnIndex': json['account_type_column_index'] == null ? undefined : json['account_type_column_index'],
        'accountTypeColumnHeader': json['account_type_column_header'] == null ? undefined : json['account_type_column_header'],
        'actionColumnIndex': json['action_column_index'] == null ? undefined : json['action_column_index'],
        'actionColumnHeader': json['action_column_header'] == null ? undefined : json['action_column_header'],
        'descriptionColumnIndex': json['description_column_index'] == null ? undefined : json['description_column_index'],
        'descriptionColumnHeader': json['description_column_header'] == null ? undefined : json['description_column_header'],
        'amountColumnIndex': json['amount_column_index'] == null ? undefined : json['amount_column_index'],
        'amountColumnHeader': json['amount_column_header'] == null ? undefined : json['amount_column_header'],
    };
}

export function CSVFieldMappingToJSON(value?: Omit<CSVFieldMapping, 'id'|'created_at'|'updated_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'has_header_row': value['hasHeaderRow'],
        'date_column_index': value['dateColumnIndex'],
        'date_column_header': value['dateColumnHeader'],
        'recipient_name_column_index': value['recipientNameColumnIndex'],
        'recipient_name_column_header': value['recipientNameColumnHeader'],
        'routing_number_column_index': value['routingNumberColumnIndex'],
        'routing_number_column_header': value['routingNumberColumnHeader'],
        'account_number_column_index': value['accountNumberColumnIndex'],
        'account_number_column_header': value['accountNumberColumnHeader'],
        'account_type_column_index': value['accountTypeColumnIndex'],
        'account_type_column_header': value['accountTypeColumnHeader'],
        'action_column_index': value['actionColumnIndex'],
        'action_column_header': value['actionColumnHeader'],
        'description_column_index': value['descriptionColumnIndex'],
        'description_column_header': value['descriptionColumnHeader'],
        'amount_column_index': value['amountColumnIndex'],
        'amount_column_header': value['amountColumnHeader'],
    };
}

