/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.6.121)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `not_found` - not_found
 * * `conflict` - conflict
 * * `internal_error` - internal_error
 * @export
 */
export const ErrorCodeEnum = {
    NotFound: 'not_found',
    Conflict: 'conflict',
    InternalError: 'internal_error'
} as const;
export type ErrorCodeEnum = typeof ErrorCodeEnum[keyof typeof ErrorCodeEnum];


export function instanceOfErrorCodeEnum(value: any): boolean {
    for (const key in ErrorCodeEnum) {
        if (Object.prototype.hasOwnProperty.call(ErrorCodeEnum, key)) {
            if ((ErrorCodeEnum as Record<string, ErrorCodeEnum>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ErrorCodeEnumFromJSON(json: any): ErrorCodeEnum {
    return ErrorCodeEnumFromJSONTyped(json, false);
}

export function ErrorCodeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorCodeEnum {
    return json as ErrorCodeEnum;
}

export function ErrorCodeEnumToJSON(value?: ErrorCodeEnum | null): any {
    return value as any;
}

