/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.2.230)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IncomeTypeEnum } from './IncomeTypeEnum';
import {
    IncomeTypeEnumFromJSON,
    IncomeTypeEnumFromJSONTyped,
    IncomeTypeEnumToJSON,
} from './IncomeTypeEnum';

/**
 * 
 * @export
 * @interface IncomeSource
 */
export interface IncomeSource {
    /**
     * 
     * @type {string}
     * @memberof IncomeSource
     */
    readonly uuid?: string;
    /**
     * 
     * @type {number}
     * @memberof IncomeSource
     */
    income: number;
    /**
     * 
     * @type {IncomeTypeEnum}
     * @memberof IncomeSource
     */
    incomeType: IncomeTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof IncomeSource
     */
    mortgageRent?: number | null;
    /**
     * 
     * @type {string}
     * @memberof IncomeSource
     */
    industry?: string;
    /**
     * 
     * @type {string}
     * @memberof IncomeSource
     */
    occupation?: string;
}

/**
 * Check if a given object implements the IncomeSource interface.
 */
export function instanceOfIncomeSource(value: object): value is IncomeSource {
    if (!('income' in value) || value['income'] === undefined) return false;
    if (!('incomeType' in value) || value['incomeType'] === undefined) return false;
    return true;
}

export function IncomeSourceFromJSON(json: any): IncomeSource {
    return IncomeSourceFromJSONTyped(json, false);
}

export function IncomeSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomeSource {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'income': json['income'],
        'incomeType': IncomeTypeEnumFromJSON(json['income_type']),
        'mortgageRent': json['mortgage_rent'] == null ? undefined : json['mortgage_rent'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'occupation': json['occupation'] == null ? undefined : json['occupation'],
    };
}

export function IncomeSourceToJSON(value?: Omit<IncomeSource, 'uuid'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'income': value['income'],
        'income_type': IncomeTypeEnumToJSON(value['incomeType']),
        'mortgage_rent': value['mortgageRent'],
        'industry': value['industry'],
        'occupation': value['occupation'],
    };
}

