/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.7.72)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaxExpediteChoiceEnum } from './MaxExpediteChoiceEnum';
import {
    MaxExpediteChoiceEnumFromJSON,
    MaxExpediteChoiceEnumFromJSONTyped,
    MaxExpediteChoiceEnumToJSON,
} from './MaxExpediteChoiceEnum';
import type { DualApprovalStateEnum } from './DualApprovalStateEnum';
import {
    DualApprovalStateEnumFromJSON,
    DualApprovalStateEnumFromJSONTyped,
    DualApprovalStateEnumToJSON,
} from './DualApprovalStateEnum';
import type { BulkPaymentTemplatePaymentData } from './BulkPaymentTemplatePaymentData';
import {
    BulkPaymentTemplatePaymentDataFromJSON,
    BulkPaymentTemplatePaymentDataFromJSONTyped,
    BulkPaymentTemplatePaymentDataToJSON,
} from './BulkPaymentTemplatePaymentData';

/**
 * Nested serializer for Group CREATE — no concurrency guard needed for the first version.
 * @export
 * @interface InitialBulkPaymentTemplateVersion
 */
export interface InitialBulkPaymentTemplateVersion {
    /**
     * 
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    readonly templateGroup?: string;
    /**
     * 
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    readonly templateGroupName?: string;
    /**
     * 
     * @type {number}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    readonly versionNumber?: number;
    /**
     * 
     * @type {DualApprovalStateEnum}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    dualApprovalState?: DualApprovalStateEnum | null;
    /**
     * 
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    readonly dualApprovalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    readonly userFullName?: string;
    /**
     * 
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    readonly userEmail?: string;
    /**
     * 
     * @type {Date}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    readonly lastUsed?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    readonly updatedAt?: Date;
    /**
     * Display name of the originating account.
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    readonly institutionAccountName?: string;
    /**
     * Last four alphanumeric characters of the originating account number.
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    readonly institutionAccountLastFour?: string;
    /**
     * 
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    name?: string | null;
    /**
     * The UUID of the originating account for the template.
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    institutionAccount: string;
    /**
     * 
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    secCode?: string | null;
    /**
     * A field that describes the purpose of the transaction to the receiver. It's used to help identify, monitor, and count payments for specific purposes.
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    entryDesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    description?: string;
    /**
     * 
     * @type {MaxExpediteChoiceEnum}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    maxExpediteChoice?: MaxExpediteChoiceEnum;
    /**
     * 
     * @type {boolean}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    groupPosting?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    note?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    userChangeLog?: string;
    /**
     * 
     * @type {Array<BulkPaymentTemplatePaymentData>}
     * @memberof InitialBulkPaymentTemplateVersion
     */
    paymentData: Array<BulkPaymentTemplatePaymentData>;
}

/**
 * Check if a given object implements the InitialBulkPaymentTemplateVersion interface.
 */
export function instanceOfInitialBulkPaymentTemplateVersion(value: object): value is InitialBulkPaymentTemplateVersion {
    if (!('institutionAccount' in value) || value['institutionAccount'] === undefined) return false;
    if (!('paymentData' in value) || value['paymentData'] === undefined) return false;
    return true;
}

export function InitialBulkPaymentTemplateVersionFromJSON(json: any): InitialBulkPaymentTemplateVersion {
    return InitialBulkPaymentTemplateVersionFromJSONTyped(json, false);
}

export function InitialBulkPaymentTemplateVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InitialBulkPaymentTemplateVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'templateGroup': json['template_group'] == null ? undefined : json['template_group'],
        'templateGroupName': json['template_group_name'] == null ? undefined : json['template_group_name'],
        'versionNumber': json['version_number'] == null ? undefined : json['version_number'],
        'dualApprovalState': json['dual_approval_state'] == null ? undefined : DualApprovalStateEnumFromJSON(json['dual_approval_state']),
        'dualApprovalId': json['dual_approval_id'] == null ? undefined : json['dual_approval_id'],
        'userFullName': json['user_full_name'] == null ? undefined : json['user_full_name'],
        'userEmail': json['user_email'] == null ? undefined : json['user_email'],
        'lastUsed': json['last_used'] == null ? undefined : (new Date(json['last_used'])),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'institutionAccountName': json['institution_account_name'] == null ? undefined : json['institution_account_name'],
        'institutionAccountLastFour': json['institution_account_last_four'] == null ? undefined : json['institution_account_last_four'],
        'name': json['name'] == null ? undefined : json['name'],
        'institutionAccount': json['institution_account'],
        'secCode': json['sec_code'] == null ? undefined : json['sec_code'],
        'entryDesc': json['entry_desc'] == null ? undefined : json['entry_desc'],
        'description': json['description'] == null ? undefined : json['description'],
        'maxExpediteChoice': json['max_expedite_choice'] == null ? undefined : MaxExpediteChoiceEnumFromJSON(json['max_expedite_choice']),
        'groupPosting': json['group_posting'] == null ? undefined : json['group_posting'],
        'note': json['note'] == null ? undefined : json['note'],
        'userChangeLog': json['user_change_log'] == null ? undefined : json['user_change_log'],
        'paymentData': ((json['payment_data'] as Array<any>).map(BulkPaymentTemplatePaymentDataFromJSON)),
    };
}

export function InitialBulkPaymentTemplateVersionToJSON(value?: Omit<InitialBulkPaymentTemplateVersion, 'id'|'template_group'|'template_group_name'|'version_number'|'dual_approval_id'|'user_full_name'|'user_email'|'last_used'|'created_at'|'updated_at'|'institution_account_name'|'institution_account_last_four'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dual_approval_state': DualApprovalStateEnumToJSON(value['dualApprovalState']),
        'name': value['name'],
        'institution_account': value['institutionAccount'],
        'sec_code': value['secCode'],
        'entry_desc': value['entryDesc'],
        'description': value['description'],
        'max_expedite_choice': MaxExpediteChoiceEnumToJSON(value['maxExpediteChoice']),
        'group_posting': value['groupPosting'],
        'note': value['note'],
        'user_change_log': value['userChangeLog'],
        'payment_data': ((value['paymentData'] as Array<any>).map(BulkPaymentTemplatePaymentDataToJSON)),
    };
}

