/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2025.8.157)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for institution features flags and settings.
 * @export
 * @interface InstitutionFeaturesContextProcessor
 */
export interface InstitutionFeaturesContextProcessor {
    /**
     * 
     * @type {boolean}
     * @memberof InstitutionFeaturesContextProcessor
     */
    readonly lending?: boolean;
}

/**
 * Check if a given object implements the InstitutionFeaturesContextProcessor interface.
 */
export function instanceOfInstitutionFeaturesContextProcessor(value: object): value is InstitutionFeaturesContextProcessor {
    return true;
}

export function InstitutionFeaturesContextProcessorFromJSON(json: any): InstitutionFeaturesContextProcessor {
    return InstitutionFeaturesContextProcessorFromJSONTyped(json, false);
}

export function InstitutionFeaturesContextProcessorFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstitutionFeaturesContextProcessor {
    if (json == null) {
        return json;
    }
    return {
        
        'lending': json['lending'] == null ? undefined : json['lending'],
    };
}

export function InstitutionFeaturesContextProcessorToJSON(value?: Omit<InstitutionFeaturesContextProcessor, 'lending'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

