/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReasonEnum } from './ReasonEnum';
import {
    ReasonEnumFromJSON,
    ReasonEnumFromJSONTyped,
    ReasonEnumToJSON,
} from './ReasonEnum';

/**
 * 
 * @export
 * @interface MissingCard
 */
export interface MissingCard {
    /**
     * 
     * @type {ReasonEnum}
     * @memberof MissingCard
     */
    reason: ReasonEnum;
}

/**
 * Check if a given object implements the MissingCard interface.
 */
export function instanceOfMissingCard(value: object): value is MissingCard {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function MissingCardFromJSON(json: any): MissingCard {
    return MissingCardFromJSONTyped(json, false);
}

export function MissingCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): MissingCard {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': ReasonEnumFromJSON(json['reason']),
    };
}

export function MissingCardToJSON(value?: MissingCard | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'reason': ReasonEnumToJSON(value['reason']),
    };
}

