/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2025.11.339)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionAlertRule } from './TransactionAlertRule';
import {
    TransactionAlertRuleFromJSON,
    TransactionAlertRuleFromJSONTyped,
    TransactionAlertRuleToJSON,
} from './TransactionAlertRule';

/**
 * 
 * @export
 * @interface PaginatedTransactionAlertRuleList
 */
export interface PaginatedTransactionAlertRuleList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTransactionAlertRuleList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTransactionAlertRuleList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTransactionAlertRuleList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<TransactionAlertRule>}
     * @memberof PaginatedTransactionAlertRuleList
     */
    results: Array<TransactionAlertRule>;
}

/**
 * Check if a given object implements the PaginatedTransactionAlertRuleList interface.
 */
export function instanceOfPaginatedTransactionAlertRuleList(value: object): value is PaginatedTransactionAlertRuleList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedTransactionAlertRuleListFromJSON(json: any): PaginatedTransactionAlertRuleList {
    return PaginatedTransactionAlertRuleListFromJSONTyped(json, false);
}

export function PaginatedTransactionAlertRuleListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTransactionAlertRuleList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(TransactionAlertRuleFromJSON)),
    };
}

export function PaginatedTransactionAlertRuleListToJSON(value?: PaginatedTransactionAlertRuleList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(TransactionAlertRuleToJSON)),
    };
}

