/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.5.324)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CSVFieldMapping } from './CSVFieldMapping';
import {
    CSVFieldMappingFromJSON,
    CSVFieldMappingFromJSONTyped,
    CSVFieldMappingToJSON,
} from './CSVFieldMapping';

/**
 * 
 * @export
 * @interface PaginatedCSVFieldMappingList
 */
export interface PaginatedCSVFieldMappingList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCSVFieldMappingList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCSVFieldMappingList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCSVFieldMappingList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<CSVFieldMapping>}
     * @memberof PaginatedCSVFieldMappingList
     */
    results: Array<CSVFieldMapping>;
}

/**
 * Check if a given object implements the PaginatedCSVFieldMappingList interface.
 */
export function instanceOfPaginatedCSVFieldMappingList(value: object): value is PaginatedCSVFieldMappingList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedCSVFieldMappingListFromJSON(json: any): PaginatedCSVFieldMappingList {
    return PaginatedCSVFieldMappingListFromJSONTyped(json, false);
}

export function PaginatedCSVFieldMappingListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCSVFieldMappingList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(CSVFieldMappingFromJSON)),
    };
}

export function PaginatedCSVFieldMappingListToJSON(value?: PaginatedCSVFieldMappingList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(CSVFieldMappingToJSON)),
    };
}

