/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.6.426)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * HATEOAS link object for the next page of results.
 * @export
 * @interface PaginatedBulkPaymentListLinksNext
 */
export interface PaginatedBulkPaymentListLinksNext {
    /**
     * 
     * @type {string}
     * @memberof PaginatedBulkPaymentListLinksNext
     */
    href?: string;
}

/**
 * Check if a given object implements the PaginatedBulkPaymentListLinksNext interface.
 */
export function instanceOfPaginatedBulkPaymentListLinksNext(value: object): value is PaginatedBulkPaymentListLinksNext {
    return true;
}

export function PaginatedBulkPaymentListLinksNextFromJSON(json: any): PaginatedBulkPaymentListLinksNext {
    return PaginatedBulkPaymentListLinksNextFromJSONTyped(json, false);
}

export function PaginatedBulkPaymentListLinksNextFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBulkPaymentListLinksNext {
    if (json == null) {
        return json;
    }
    return {
        
        'href': json['href'] == null ? undefined : json['href'],
    };
}

export function PaginatedBulkPaymentListLinksNextToJSON(value?: PaginatedBulkPaymentListLinksNext | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'href': value['href'],
    };
}

