/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.8.43)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataAccessConsent } from './DataAccessConsent';
import {
    DataAccessConsentFromJSON,
    DataAccessConsentFromJSONTyped,
    DataAccessConsentToJSON,
} from './DataAccessConsent';

/**
 * 
 * @export
 * @interface PaginatedDataAccessConsentList
 */
export interface PaginatedDataAccessConsentList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedDataAccessConsentList
     */
    count: number;
    /**
     * 
     * @type {Array<DataAccessConsent>}
     * @memberof PaginatedDataAccessConsentList
     */
    results: Array<DataAccessConsent>;
}

/**
 * Check if a given object implements the PaginatedDataAccessConsentList interface.
 */
export function instanceOfPaginatedDataAccessConsentList(value: object): value is PaginatedDataAccessConsentList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedDataAccessConsentListFromJSON(json: any): PaginatedDataAccessConsentList {
    return PaginatedDataAccessConsentListFromJSONTyped(json, false);
}

export function PaginatedDataAccessConsentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedDataAccessConsentList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'results': ((json['results'] as Array<any>).map(DataAccessConsentFromJSON)),
    };
}

export function PaginatedDataAccessConsentListToJSON(value?: PaginatedDataAccessConsentList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'results': ((value['results'] as Array<any>).map(DataAccessConsentToJSON)),
    };
}

