/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.6.214)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedWireCSVFieldMappingRequest
 */
export interface PatchedWireCSVFieldMappingRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    hasHeaderRow?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    recipientNameColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    recipientNameColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    routingNumberColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    routingNumberColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    accountNumberColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    accountNumberColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    amountColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    amountColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    memoColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    memoColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    wireReasonColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    wireReasonColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    recipientStreetAddressColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    recipientStreetAddressColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    recipientCityColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    recipientCityColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    recipientRegionCodeColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    recipientRegionCodeColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    recipientPostalCodeColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedWireCSVFieldMappingRequest
     */
    recipientPostalCodeColumnHeader?: string | null;
}

/**
 * Check if a given object implements the PatchedWireCSVFieldMappingRequest interface.
 */
export function instanceOfPatchedWireCSVFieldMappingRequest(value: object): value is PatchedWireCSVFieldMappingRequest {
    return true;
}

export function PatchedWireCSVFieldMappingRequestFromJSON(json: any): PatchedWireCSVFieldMappingRequest {
    return PatchedWireCSVFieldMappingRequestFromJSONTyped(json, false);
}

export function PatchedWireCSVFieldMappingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedWireCSVFieldMappingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'hasHeaderRow': json['has_header_row'] == null ? undefined : json['has_header_row'],
        'recipientNameColumnIndex': json['recipient_name_column_index'] == null ? undefined : json['recipient_name_column_index'],
        'recipientNameColumnHeader': json['recipient_name_column_header'] == null ? undefined : json['recipient_name_column_header'],
        'routingNumberColumnIndex': json['routing_number_column_index'] == null ? undefined : json['routing_number_column_index'],
        'routingNumberColumnHeader': json['routing_number_column_header'] == null ? undefined : json['routing_number_column_header'],
        'accountNumberColumnIndex': json['account_number_column_index'] == null ? undefined : json['account_number_column_index'],
        'accountNumberColumnHeader': json['account_number_column_header'] == null ? undefined : json['account_number_column_header'],
        'amountColumnIndex': json['amount_column_index'] == null ? undefined : json['amount_column_index'],
        'amountColumnHeader': json['amount_column_header'] == null ? undefined : json['amount_column_header'],
        'memoColumnIndex': json['memo_column_index'] == null ? undefined : json['memo_column_index'],
        'memoColumnHeader': json['memo_column_header'] == null ? undefined : json['memo_column_header'],
        'wireReasonColumnIndex': json['wire_reason_column_index'] == null ? undefined : json['wire_reason_column_index'],
        'wireReasonColumnHeader': json['wire_reason_column_header'] == null ? undefined : json['wire_reason_column_header'],
        'recipientStreetAddressColumnIndex': json['recipient_street_address_column_index'] == null ? undefined : json['recipient_street_address_column_index'],
        'recipientStreetAddressColumnHeader': json['recipient_street_address_column_header'] == null ? undefined : json['recipient_street_address_column_header'],
        'recipientCityColumnIndex': json['recipient_city_column_index'] == null ? undefined : json['recipient_city_column_index'],
        'recipientCityColumnHeader': json['recipient_city_column_header'] == null ? undefined : json['recipient_city_column_header'],
        'recipientRegionCodeColumnIndex': json['recipient_region_code_column_index'] == null ? undefined : json['recipient_region_code_column_index'],
        'recipientRegionCodeColumnHeader': json['recipient_region_code_column_header'] == null ? undefined : json['recipient_region_code_column_header'],
        'recipientPostalCodeColumnIndex': json['recipient_postal_code_column_index'] == null ? undefined : json['recipient_postal_code_column_index'],
        'recipientPostalCodeColumnHeader': json['recipient_postal_code_column_header'] == null ? undefined : json['recipient_postal_code_column_header'],
    };
}

export function PatchedWireCSVFieldMappingRequestToJSON(value?: PatchedWireCSVFieldMappingRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'has_header_row': value['hasHeaderRow'],
        'recipient_name_column_index': value['recipientNameColumnIndex'],
        'recipient_name_column_header': value['recipientNameColumnHeader'],
        'routing_number_column_index': value['routingNumberColumnIndex'],
        'routing_number_column_header': value['routingNumberColumnHeader'],
        'account_number_column_index': value['accountNumberColumnIndex'],
        'account_number_column_header': value['accountNumberColumnHeader'],
        'amount_column_index': value['amountColumnIndex'],
        'amount_column_header': value['amountColumnHeader'],
        'memo_column_index': value['memoColumnIndex'],
        'memo_column_header': value['memoColumnHeader'],
        'wire_reason_column_index': value['wireReasonColumnIndex'],
        'wire_reason_column_header': value['wireReasonColumnHeader'],
        'recipient_street_address_column_index': value['recipientStreetAddressColumnIndex'],
        'recipient_street_address_column_header': value['recipientStreetAddressColumnHeader'],
        'recipient_city_column_index': value['recipientCityColumnIndex'],
        'recipient_city_column_header': value['recipientCityColumnHeader'],
        'recipient_region_code_column_index': value['recipientRegionCodeColumnIndex'],
        'recipient_region_code_column_header': value['recipientRegionCodeColumnHeader'],
        'recipient_postal_code_column_index': value['recipientPostalCodeColumnIndex'],
        'recipient_postal_code_column_header': value['recipientPostalCodeColumnHeader'],
    };
}

