/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.4.132)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedSwiftWireTemplateRequest
 */
export interface PatchedSwiftWireTemplateRequest {
    /**
     * The UUID of the recipient for swiftwires sent using this template.
     * @type {string}
     * @memberof PatchedSwiftWireTemplateRequest
     */
    recipient?: string;
    /**
     * The UUID of the source account for swiftwires sent using this template.
     * @type {string}
     * @memberof PatchedSwiftWireTemplateRequest
     */
    fromAccount?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSwiftWireTemplateRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSwiftWireTemplateRequest
     */
    wireReason?: string | null;
    /**
     * A field that returns the original value in the currency's smallest unit (e.g. cents).
     * @type {number}
     * @memberof PatchedSwiftWireTemplateRequest
     */
    amount?: number | null;
    /**
     * ISO 4217 currency code the amount is denominated in (e.g. 'USD' or the recipient's currency).
     * @type {string}
     * @memberof PatchedSwiftWireTemplateRequest
     */
    amountCurrency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedSwiftWireTemplateRequest
     */
    memo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedSwiftWireTemplateRequest
     */
    note?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedSwiftWireTemplateRequest
     */
    recipientCurrency?: string;
}

/**
 * Check if a given object implements the PatchedSwiftWireTemplateRequest interface.
 */
export function instanceOfPatchedSwiftWireTemplateRequest(value: object): value is PatchedSwiftWireTemplateRequest {
    return true;
}

export function PatchedSwiftWireTemplateRequestFromJSON(json: any): PatchedSwiftWireTemplateRequest {
    return PatchedSwiftWireTemplateRequestFromJSONTyped(json, false);
}

export function PatchedSwiftWireTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSwiftWireTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recipient': json['recipient'] == null ? undefined : json['recipient'],
        'fromAccount': json['from_account'] == null ? undefined : json['from_account'],
        'name': json['name'] == null ? undefined : json['name'],
        'wireReason': json['wire_reason'] == null ? undefined : json['wire_reason'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'amountCurrency': json['amount_currency'] == null ? undefined : json['amount_currency'],
        'memo': json['memo'] == null ? undefined : json['memo'],
        'note': json['note'] == null ? undefined : json['note'],
        'recipientCurrency': json['recipient_currency'] == null ? undefined : json['recipient_currency'],
    };
}

export function PatchedSwiftWireTemplateRequestToJSON(value?: PatchedSwiftWireTemplateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'recipient': value['recipient'],
        'from_account': value['fromAccount'],
        'name': value['name'],
        'wire_reason': value['wireReason'],
        'amount': value['amount'],
        'amount_currency': value['amountCurrency'],
        'memo': value['memo'],
        'note': value['note'],
        'recipient_currency': value['recipientCurrency'],
    };
}

