/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.6.319)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReceiptSuggestionBatchSummary
 */
export interface ReceiptSuggestionBatchSummary {
    /**
     * 
     * @type {number}
     * @memberof ReceiptSuggestionBatchSummary
     */
    succeeded: number;
    /**
     * 
     * @type {number}
     * @memberof ReceiptSuggestionBatchSummary
     */
    failed: number;
    /**
     * 
     * @type {number}
     * @memberof ReceiptSuggestionBatchSummary
     */
    total: number;
}

/**
 * Check if a given object implements the ReceiptSuggestionBatchSummary interface.
 */
export function instanceOfReceiptSuggestionBatchSummary(value: object): value is ReceiptSuggestionBatchSummary {
    if (!('succeeded' in value) || value['succeeded'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ReceiptSuggestionBatchSummaryFromJSON(json: any): ReceiptSuggestionBatchSummary {
    return ReceiptSuggestionBatchSummaryFromJSONTyped(json, false);
}

export function ReceiptSuggestionBatchSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptSuggestionBatchSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'succeeded': json['succeeded'],
        'failed': json['failed'],
        'total': json['total'],
    };
}

export function ReceiptSuggestionBatchSummaryToJSON(value?: ReceiptSuggestionBatchSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'succeeded': value['succeeded'],
        'failed': value['failed'],
        'total': value['total'],
    };
}

