/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.7.2)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response payload for GET /v1/receipts/config.
 * @export
 * @interface ReceiptUploadConfig
 */
export interface ReceiptUploadConfig {
    /**
     * 
     * @type {Array<string>}
     * @memberof ReceiptUploadConfig
     */
    allowedMimeTypes: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ReceiptUploadConfig
     */
    maxSizeBytes: number;
}

/**
 * Check if a given object implements the ReceiptUploadConfig interface.
 */
export function instanceOfReceiptUploadConfig(value: object): value is ReceiptUploadConfig {
    if (!('allowedMimeTypes' in value) || value['allowedMimeTypes'] === undefined) return false;
    if (!('maxSizeBytes' in value) || value['maxSizeBytes'] === undefined) return false;
    return true;
}

export function ReceiptUploadConfigFromJSON(json: any): ReceiptUploadConfig {
    return ReceiptUploadConfigFromJSONTyped(json, false);
}

export function ReceiptUploadConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptUploadConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'allowedMimeTypes': json['allowed_mime_types'],
        'maxSizeBytes': json['max_size_bytes'],
    };
}

export function ReceiptUploadConfigToJSON(value?: ReceiptUploadConfig | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'allowed_mime_types': value['allowedMimeTypes'],
        'max_size_bytes': value['maxSizeBytes'],
    };
}

