/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.6.347)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `success` - success
 * * `failed` - failed
 * @export
 */
export const ReceiptSuggestionBatchResultStatusEnum = {
    Success: 'success',
    Failed: 'failed'
} as const;
export type ReceiptSuggestionBatchResultStatusEnum = typeof ReceiptSuggestionBatchResultStatusEnum[keyof typeof ReceiptSuggestionBatchResultStatusEnum];


export function instanceOfReceiptSuggestionBatchResultStatusEnum(value: any): boolean {
    for (const key in ReceiptSuggestionBatchResultStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(ReceiptSuggestionBatchResultStatusEnum, key)) {
            if ((ReceiptSuggestionBatchResultStatusEnum as Record<string, ReceiptSuggestionBatchResultStatusEnum>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReceiptSuggestionBatchResultStatusEnumFromJSON(json: any): ReceiptSuggestionBatchResultStatusEnum {
    return ReceiptSuggestionBatchResultStatusEnumFromJSONTyped(json, false);
}

export function ReceiptSuggestionBatchResultStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptSuggestionBatchResultStatusEnum {
    return json as ReceiptSuggestionBatchResultStatusEnum;
}

export function ReceiptSuggestionBatchResultStatusEnumToJSON(value?: ReceiptSuggestionBatchResultStatusEnum | null): any {
    return value as any;
}

