/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.7.196)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReceiptSuggestion } from './ReceiptSuggestion';
import {
    ReceiptSuggestionFromJSON,
    ReceiptSuggestionFromJSONTyped,
    ReceiptSuggestionToJSON,
} from './ReceiptSuggestion';

/**
 * Response shape for GET /v1/receipts/<uuid>/.
 * 
 * The view must populate `image_url` (presigned S3 URL) and `suggestion`
 * (top-1 PRESENTED suggestion, or None) directly on the Receipt instance
 * before serialization — those are derived fields, not model columns.
 * @export
 * @interface ReceiptDetail
 */
export interface ReceiptDetail {
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    readonly merchant?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    readonly transactionDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    readonly amount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    imageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    imageMimeType: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    thumbnailUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    largeThumbnailUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    downloadUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    originalFilename: string;
    /**
     * 
     * @type {ReceiptSuggestion}
     * @memberof ReceiptDetail
     */
    suggestion: ReceiptSuggestion | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ReceiptDetail
     */
    readonly uploadedBy?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    readonly uploadedAt?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ReceiptDetail
     */
    readonly approvedBy?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    readonly approvedAt?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ReceiptDetail
     */
    readonly rejectedBy?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    readonly rejectedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    noMatchReason: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    readonly retryExpiresAt?: string | null;
}

/**
 * Check if a given object implements the ReceiptDetail interface.
 */
export function instanceOfReceiptDetail(value: object): value is ReceiptDetail {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('imageMimeType' in value) || value['imageMimeType'] === undefined) return false;
    if (!('thumbnailUrl' in value) || value['thumbnailUrl'] === undefined) return false;
    if (!('largeThumbnailUrl' in value) || value['largeThumbnailUrl'] === undefined) return false;
    if (!('downloadUrl' in value) || value['downloadUrl'] === undefined) return false;
    if (!('originalFilename' in value) || value['originalFilename'] === undefined) return false;
    if (!('suggestion' in value) || value['suggestion'] === undefined) return false;
    if (!('noMatchReason' in value) || value['noMatchReason'] === undefined) return false;
    return true;
}

export function ReceiptDetailFromJSON(json: any): ReceiptDetail {
    return ReceiptDetailFromJSONTyped(json, false);
}

export function ReceiptDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'status': json['status'],
        'merchant': json['merchant'] == null ? undefined : json['merchant'],
        'transactionDate': json['transaction_date'] == null ? undefined : json['transaction_date'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'imageUrl': json['image_url'],
        'imageMimeType': json['image_mime_type'],
        'thumbnailUrl': json['thumbnail_url'],
        'largeThumbnailUrl': json['large_thumbnail_url'],
        'downloadUrl': json['download_url'],
        'originalFilename': json['original_filename'],
        'suggestion': ReceiptSuggestionFromJSON(json['suggestion']),
        'uploadedBy': json['uploaded_by'] == null ? undefined : json['uploaded_by'],
        'uploadedAt': json['uploaded_at'] == null ? undefined : json['uploaded_at'],
        'approvedBy': json['approved_by'] == null ? undefined : json['approved_by'],
        'approvedAt': json['approved_at'] == null ? undefined : json['approved_at'],
        'rejectedBy': json['rejected_by'] == null ? undefined : json['rejected_by'],
        'rejectedAt': json['rejected_at'] == null ? undefined : json['rejected_at'],
        'noMatchReason': json['no_match_reason'],
        'retryExpiresAt': json['retry_expires_at'] == null ? undefined : json['retry_expires_at'],
    };
}

export function ReceiptDetailToJSON(value?: Omit<ReceiptDetail, 'merchant'|'transaction_date'|'amount'|'uploaded_by'|'uploaded_at'|'approved_by'|'approved_at'|'rejected_by'|'rejected_at'|'retry_expires_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'uuid': value['uuid'],
        'status': value['status'],
        'image_url': value['imageUrl'],
        'image_mime_type': value['imageMimeType'],
        'thumbnail_url': value['thumbnailUrl'],
        'large_thumbnail_url': value['largeThumbnailUrl'],
        'download_url': value['downloadUrl'],
        'original_filename': value['originalFilename'],
        'suggestion': ReceiptSuggestionToJSON(value['suggestion']),
        'no_match_reason': value['noMatchReason'],
    };
}

