/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2025.6.141)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlankEnum } from './BlankEnum';
import {
    instanceOfBlankEnum,
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { SubscriptionFrequencyEnum } from './SubscriptionFrequencyEnum';
import {
    instanceOfSubscriptionFrequencyEnum,
    SubscriptionFrequencyEnumFromJSON,
    SubscriptionFrequencyEnumFromJSONTyped,
    SubscriptionFrequencyEnumToJSON,
} from './SubscriptionFrequencyEnum';

/**
 * @type RecurringTransactionSubscriptionFrequency
 * 
 * @export
 */
export type RecurringTransactionSubscriptionFrequency = BlankEnum | SubscriptionFrequencyEnum;

export function RecurringTransactionSubscriptionFrequencyFromJSON(json: any): RecurringTransactionSubscriptionFrequency {
    return RecurringTransactionSubscriptionFrequencyFromJSONTyped(json, false);
}

export function RecurringTransactionSubscriptionFrequencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringTransactionSubscriptionFrequency {
    if (json == null) {
        return json;
    }
    if (instanceOfBlankEnum(json)) {
        return BlankEnumFromJSONTyped(json, true);
    }
    if (instanceOfSubscriptionFrequencyEnum(json)) {
        return SubscriptionFrequencyEnumFromJSONTyped(json, true);
    }
}

export function RecurringTransactionSubscriptionFrequencyToJSON(value?: RecurringTransactionSubscriptionFrequency | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfBlankEnum(value)) {
        return BlankEnumToJSON(value as BlankEnum);
    }
    if (instanceOfSubscriptionFrequencyEnum(value)) {
        return SubscriptionFrequencyEnumToJSON(value as SubscriptionFrequencyEnum);
    }

    return {};
}

