/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.7.372)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `INCORRECT_AMOUNT` - Incorrect amount
 * * `INCORRECT_ACCOUNT` - Incorrect account
 * * `DUPLICATE` - Duplicate
 * @export
 */
export const ReversalReasonEnum = {
    IncorrectAmount: 'INCORRECT_AMOUNT',
    IncorrectAccount: 'INCORRECT_ACCOUNT',
    Duplicate: 'DUPLICATE'
} as const;
export type ReversalReasonEnum = typeof ReversalReasonEnum[keyof typeof ReversalReasonEnum];


export function instanceOfReversalReasonEnum(value: any): boolean {
    for (const key in ReversalReasonEnum) {
        if (Object.prototype.hasOwnProperty.call(ReversalReasonEnum, key)) {
            if ((ReversalReasonEnum as Record<string, ReversalReasonEnum>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReversalReasonEnumFromJSON(json: any): ReversalReasonEnum {
    return ReversalReasonEnumFromJSONTyped(json, false);
}

export function ReversalReasonEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReversalReasonEnum {
    return json as ReversalReasonEnum;
}

export function ReversalReasonEnumToJSON(value?: ReversalReasonEnum | null): any {
    return value as any;
}

