/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.6.369)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwiftWireTemplate
 */
export interface SwiftWireTemplate {
    /**
     * Date when the template was last used to send a swiftwire.
     * @type {Date}
     * @memberof SwiftWireTemplate
     */
    readonly lastUsed?: Date | null;
    /**
     * The version ID of the template, based on when template or recipient details were last updated.
     * @type {string}
     * @memberof SwiftWireTemplate
     */
    readonly versionId?: string;
    /**
     * Human-readable description of the wire_reason purpose code, resolved from the recipient's BIC.
     * @type {string}
     * @memberof SwiftWireTemplate
     */
    readonly wireReasonDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SwiftWireTemplate
     */
    readonly id?: string;
    /**
     * The UUID of the recipient for swiftwires sent using this template.
     * @type {string}
     * @memberof SwiftWireTemplate
     */
    recipient: string;
    /**
     * The UUID of the source account for swiftwires sent using this template.
     * @type {string}
     * @memberof SwiftWireTemplate
     */
    fromAccount: string;
    /**
     * 
     * @type {string}
     * @memberof SwiftWireTemplate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SwiftWireTemplate
     */
    wireReason?: string | null;
    /**
     * Amount in the currency's natural unit (e.g. 100.00 for $100 USD, 10000 for ¥10000 JPY).
     * @type {number}
     * @memberof SwiftWireTemplate
     */
    amount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SwiftWireTemplate
     */
    amountCurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof SwiftWireTemplate
     */
    memo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SwiftWireTemplate
     */
    note?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SwiftWireTemplate
     */
    recipientCurrency?: string | null;
}

/**
 * Check if a given object implements the SwiftWireTemplate interface.
 */
export function instanceOfSwiftWireTemplate(value: object): value is SwiftWireTemplate {
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if (!('fromAccount' in value) || value['fromAccount'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SwiftWireTemplateFromJSON(json: any): SwiftWireTemplate {
    return SwiftWireTemplateFromJSONTyped(json, false);
}

export function SwiftWireTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwiftWireTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'lastUsed': json['last_used'] == null ? undefined : (new Date(json['last_used'])),
        'versionId': json['version_id'] == null ? undefined : json['version_id'],
        'wireReasonDescription': json['wire_reason_description'] == null ? undefined : json['wire_reason_description'],
        'id': json['id'] == null ? undefined : json['id'],
        'recipient': json['recipient'],
        'fromAccount': json['from_account'],
        'name': json['name'],
        'wireReason': json['wire_reason'] == null ? undefined : json['wire_reason'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'amountCurrency': json['amount_currency'] == null ? undefined : json['amount_currency'],
        'memo': json['memo'] == null ? undefined : json['memo'],
        'note': json['note'] == null ? undefined : json['note'],
        'recipientCurrency': json['recipient_currency'] == null ? undefined : json['recipient_currency'],
    };
}

export function SwiftWireTemplateToJSON(value?: Omit<SwiftWireTemplate, 'last_used'|'version_id'|'wire_reason_description'|'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'recipient': value['recipient'],
        'from_account': value['fromAccount'],
        'name': value['name'],
        'wire_reason': value['wireReason'],
        'amount': value['amount'],
        'amount_currency': value['amountCurrency'],
        'memo': value['memo'],
        'note': value['note'],
        'recipient_currency': value['recipientCurrency'],
    };
}

