/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2025.10.106)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WireRecipientAddress } from './WireRecipientAddress';
import {
    WireRecipientAddressFromJSON,
    WireRecipientAddressFromJSONTyped,
    WireRecipientAddressToJSON,
} from './WireRecipientAddress';

/**
 * 
 * @export
 * @interface SwiftWireDestination
 */
export interface SwiftWireDestination {
    /**
     * 
     * @type {string}
     * @memberof SwiftWireDestination
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof SwiftWireDestination
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SwiftWireDestination
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof SwiftWireDestination
     */
    bic: string;
    /**
     * 
     * @type {any}
     * @memberof SwiftWireDestination
     */
    metadata?: any | null;
    /**
     * 
     * @type {WireRecipientAddress}
     * @memberof SwiftWireDestination
     */
    address: WireRecipientAddress;
    /**
     * Account identifier (IBAN, account number, phone) for the Swift wire destination.
     * @type {string}
     * @memberof SwiftWireDestination
     */
    accountIdentifier: string;
    /**
     * 
     * @type {WireRecipientAddress}
     * @memberof SwiftWireDestination
     */
    branchAddress?: WireRecipientAddress | null;
}

/**
 * Check if a given object implements the SwiftWireDestination interface.
 */
export function instanceOfSwiftWireDestination(value: object): value is SwiftWireDestination {
    if (!('bic' in value) || value['bic'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('accountIdentifier' in value) || value['accountIdentifier'] === undefined) return false;
    return true;
}

export function SwiftWireDestinationFromJSON(json: any): SwiftWireDestination {
    return SwiftWireDestinationFromJSONTyped(json, false);
}

export function SwiftWireDestinationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwiftWireDestination {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'bic': json['bic'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'address': WireRecipientAddressFromJSON(json['address']),
        'accountIdentifier': json['account_identifier'],
        'branchAddress': json['branch_address'] == null ? undefined : WireRecipientAddressFromJSON(json['branch_address']),
    };
}

export function SwiftWireDestinationToJSON(value?: Omit<SwiftWireDestination, 'id'|'created_at'|'updated_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bic': value['bic'],
        'metadata': value['metadata'],
        'address': WireRecipientAddressToJSON(value['address']),
        'account_identifier': value['accountIdentifier'],
        'branch_address': WireRecipientAddressToJSON(value['branchAddress']),
    };
}

