/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2025.12.59)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WireRecipientAddressRequest } from './WireRecipientAddressRequest';
import {
    WireRecipientAddressRequestFromJSON,
    WireRecipientAddressRequestFromJSONTyped,
    WireRecipientAddressRequestToJSON,
} from './WireRecipientAddressRequest';

/**
 * 
 * @export
 * @interface SwiftWireDestinationRequest
 */
export interface SwiftWireDestinationRequest {
    /**
     * 
     * @type {string}
     * @memberof SwiftWireDestinationRequest
     */
    bic: string;
    /**
     * 
     * @type {any}
     * @memberof SwiftWireDestinationRequest
     */
    metadata?: any | null;
    /**
     * UUID of the recipient associated with this Fedwire destination.
     * @type {string}
     * @memberof SwiftWireDestinationRequest
     */
    recipient: string;
    /**
     * 
     * @type {WireRecipientAddressRequest}
     * @memberof SwiftWireDestinationRequest
     */
    address: WireRecipientAddressRequest;
    /**
     * Account identifier (IBAN, account number, phone) for the Swift wire destination.
     * @type {string}
     * @memberof SwiftWireDestinationRequest
     */
    accountIdentifier: string;
    /**
     * 
     * @type {WireRecipientAddressRequest}
     * @memberof SwiftWireDestinationRequest
     */
    branchAddress?: WireRecipientAddressRequest | null;
}

/**
 * Check if a given object implements the SwiftWireDestinationRequest interface.
 */
export function instanceOfSwiftWireDestinationRequest(value: object): value is SwiftWireDestinationRequest {
    if (!('bic' in value) || value['bic'] === undefined) return false;
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('accountIdentifier' in value) || value['accountIdentifier'] === undefined) return false;
    return true;
}

export function SwiftWireDestinationRequestFromJSON(json: any): SwiftWireDestinationRequest {
    return SwiftWireDestinationRequestFromJSONTyped(json, false);
}

export function SwiftWireDestinationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwiftWireDestinationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bic': json['bic'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'recipient': json['recipient'],
        'address': WireRecipientAddressRequestFromJSON(json['address']),
        'accountIdentifier': json['account_identifier'],
        'branchAddress': json['branch_address'] == null ? undefined : WireRecipientAddressRequestFromJSON(json['branch_address']),
    };
}

export function SwiftWireDestinationRequestToJSON(value?: SwiftWireDestinationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bic': value['bic'],
        'metadata': value['metadata'],
        'recipient': value['recipient'],
        'address': WireRecipientAddressRequestToJSON(value['address']),
        'account_identifier': value['accountIdentifier'],
        'branch_address': WireRecipientAddressRequestToJSON(value['branchAddress']),
    };
}

