/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.3.118)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for file uploads to threads that validates both URL and signature.
 * @export
 * @interface ThreadFileRequest
 */
export interface ThreadFileRequest {
    /**
     * 
     * @type {string}
     * @memberof ThreadFileRequest
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof ThreadFileRequest
     */
    signature: string;
}

/**
 * Check if a given object implements the ThreadFileRequest interface.
 */
export function instanceOfThreadFileRequest(value: object): value is ThreadFileRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function ThreadFileRequestFromJSON(json: any): ThreadFileRequest {
    return ThreadFileRequestFromJSONTyped(json, false);
}

export function ThreadFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'signature': json['signature'],
    };
}

export function ThreadFileRequestToJSON(value?: ThreadFileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'signature': value['signature'],
    };
}

