/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThreadCreate
 */
export interface ThreadCreate {
    /**
     * Subject of the thread.
     * @type {string}
     * @memberof ThreadCreate
     */
    subject: string;
    /**
     * Text content of the initial message for this thread.
     * @type {string}
     * @memberof ThreadCreate
     */
    body?: string;
    /**
     * Link to the file uploaded to this thread, if applicable.
     * @type {string}
     * @memberof ThreadCreate
     */
    url?: string;
    /**
     * Identifier for relevant team.
     * @type {string}
     * @memberof ThreadCreate
     */
    teamUuid?: string;
}

/**
 * Check if a given object implements the ThreadCreate interface.
 */
export function instanceOfThreadCreate(value: object): value is ThreadCreate {
    if (!('subject' in value) || value['subject'] === undefined) return false;
    return true;
}

export function ThreadCreateFromJSON(json: any): ThreadCreate {
    return ThreadCreateFromJSONTyped(json, false);
}

export function ThreadCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'subject': json['subject'],
        'body': json['body'] == null ? undefined : json['body'],
        'url': json['url'] == null ? undefined : json['url'],
        'teamUuid': json['team_uuid'] == null ? undefined : json['team_uuid'],
    };
}

export function ThreadCreateToJSON(value?: ThreadCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'subject': value['subject'],
        'body': value['body'],
        'url': value['url'],
        'team_uuid': value['teamUuid'],
    };
}

