/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.7.183)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `analyzing` - Analyzing
 * * `pending` - Pending
 * * `processing` - Processing
 * * `processed` - Processed (in transit)
 * * `rejected` - Rejected by staff
 * * `review` - Review
 * * `canceled_by_system` - Canceled by system
 * * `canceled_by_user` - Canceled by user
 * * `expired` - Reversal expired
 * * `approved` - Dual approval approved
 * * `awaiting_approval` - Awaiting dual approval
 * * `rejected_approval` - Dual approval rejected
 * * `canceled` - Canceled
 * * `approval_expired` - Dual approval expired
 * * `awaiting_bulk_approval` - Awaiting bulk approval
 * * `rejected_bulk_approval` - Rejected bulk approval
 * @export
 */
export const UnverifiedACHReversalStateEnum = {
    Analyzing: 'analyzing',
    Pending: 'pending',
    Processing: 'processing',
    Processed: 'processed',
    Rejected: 'rejected',
    Review: 'review',
    CanceledBySystem: 'canceled_by_system',
    CanceledByUser: 'canceled_by_user',
    Expired: 'expired',
    Approved: 'approved',
    AwaitingApproval: 'awaiting_approval',
    RejectedApproval: 'rejected_approval',
    Canceled: 'canceled',
    ApprovalExpired: 'approval_expired',
    AwaitingBulkApproval: 'awaiting_bulk_approval',
    RejectedBulkApproval: 'rejected_bulk_approval'
} as const;
export type UnverifiedACHReversalStateEnum = typeof UnverifiedACHReversalStateEnum[keyof typeof UnverifiedACHReversalStateEnum];


export function instanceOfUnverifiedACHReversalStateEnum(value: any): boolean {
    for (const key in UnverifiedACHReversalStateEnum) {
        if (Object.prototype.hasOwnProperty.call(UnverifiedACHReversalStateEnum, key)) {
            if ((UnverifiedACHReversalStateEnum as Record<string, UnverifiedACHReversalStateEnum>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UnverifiedACHReversalStateEnumFromJSON(json: any): UnverifiedACHReversalStateEnum {
    return UnverifiedACHReversalStateEnumFromJSONTyped(json, false);
}

export function UnverifiedACHReversalStateEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnverifiedACHReversalStateEnum {
    return json as UnverifiedACHReversalStateEnum;
}

export function UnverifiedACHReversalStateEnumToJSON(value?: UnverifiedACHReversalStateEnum | null): any {
    return value as any;
}

