/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.8.308)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColorModeContrastEnum } from './ColorModeContrastEnum';
import {
    ColorModeContrastEnumFromJSON,
    ColorModeContrastEnumFromJSONTyped,
    ColorModeContrastEnumToJSON,
} from './ColorModeContrastEnum';

/**
 * Serializer for the authenticated user's accessibility preferences.
 * 
 * Emits raw enum values; clients are responsible for resolving display
 * labels (e.g. via a localization library keyed by the enum value).
 * @export
 * @interface UserAccessibilityPreferencesRequest
 */
export interface UserAccessibilityPreferencesRequest {
    /**
     * 
     * @type {ColorModeContrastEnum}
     * @memberof UserAccessibilityPreferencesRequest
     */
    colorModeContrast?: ColorModeContrastEnum;
}

/**
 * Check if a given object implements the UserAccessibilityPreferencesRequest interface.
 */
export function instanceOfUserAccessibilityPreferencesRequest(value: object): value is UserAccessibilityPreferencesRequest {
    return true;
}

export function UserAccessibilityPreferencesRequestFromJSON(json: any): UserAccessibilityPreferencesRequest {
    return UserAccessibilityPreferencesRequestFromJSONTyped(json, false);
}

export function UserAccessibilityPreferencesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAccessibilityPreferencesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'colorModeContrast': json['color_mode_contrast'] == null ? undefined : ColorModeContrastEnumFromJSON(json['color_mode_contrast']),
    };
}

export function UserAccessibilityPreferencesRequestToJSON(value?: UserAccessibilityPreferencesRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'color_mode_contrast': ColorModeContrastEnumToJSON(value['colorModeContrast']),
    };
}

