/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.2.66)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserCategory4f2Enum = {
    Personal: 'personal',
    Business: 'business'
} as const;
export type UserCategory4f2Enum = typeof UserCategory4f2Enum[keyof typeof UserCategory4f2Enum];


export function instanceOfUserCategory4f2Enum(value: any): boolean {
    for (const key in UserCategory4f2Enum) {
        if (Object.prototype.hasOwnProperty.call(UserCategory4f2Enum, key)) {
            if ((UserCategory4f2Enum as Record<string, UserCategory4f2Enum>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserCategory4f2EnumFromJSON(json: any): UserCategory4f2Enum {
    return UserCategory4f2EnumFromJSONTyped(json, false);
}

export function UserCategory4f2EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCategory4f2Enum {
    return json as UserCategory4f2Enum;
}

export function UserCategory4f2EnumToJSON(value?: UserCategory4f2Enum | null): any {
    return value as any;
}

