/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.7.185)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for a single row's validation errors in the wire import recipients error response.
 * @export
 * @interface WireImportRecipientRowError
 */
export interface WireImportRecipientRowError {
    /**
     * Zero-based index of the row that failed validation.
     * @type {number}
     * @memberof WireImportRecipientRowError
     */
    index: number;
    /**
     * Map of field name to error message.
     * @type {{ [key: string]: string; }}
     * @memberof WireImportRecipientRowError
     */
    errors: { [key: string]: string; };
}

/**
 * Check if a given object implements the WireImportRecipientRowError interface.
 */
export function instanceOfWireImportRecipientRowError(value: object): value is WireImportRecipientRowError {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function WireImportRecipientRowErrorFromJSON(json: any): WireImportRecipientRowError {
    return WireImportRecipientRowErrorFromJSONTyped(json, false);
}

export function WireImportRecipientRowErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): WireImportRecipientRowError {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'errors': json['errors'],
    };
}

export function WireImportRecipientRowErrorToJSON(value?: WireImportRecipientRowError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'errors': value['errors'],
    };
}

