/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.3.45)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Wire
 */
export interface Wire {
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Wire
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Wire
     */
    readonly processedAt?: Date;
    /**
     * A field that returns the original value in the currency's smallest unit (e.g. cents).
     * @type {number}
     * @memberof Wire
     */
    readonly amount?: number;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly fromAccount?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly fromAccountDisplay?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly toAccountNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly toAccountRoutingNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly toAccountInstitutionName?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly beneficiaryName?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly beneficiaryAddress1?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly beneficiaryAddress2?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly beneficiaryAddress3?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly memo1?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly memo2?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly memo3?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly memo4?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly state?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly displayState?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly templateName?: string;
    /**
     * 
     * @type {string}
     * @memberof Wire
     */
    readonly wireReason?: string;
}

/**
 * Check if a given object implements the Wire interface.
 */
export function instanceOfWire(value: object): value is Wire {
    return true;
}

export function WireFromJSON(json: any): Wire {
    return WireFromJSONTyped(json, false);
}

export function WireFromJSONTyped(json: any, ignoreDiscriminator: boolean): Wire {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'processedAt': json['processed_at'] == null ? undefined : (new Date(json['processed_at'])),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'fromAccount': json['from_account'] == null ? undefined : json['from_account'],
        'fromAccountDisplay': json['from_account_display'] == null ? undefined : json['from_account_display'],
        'toAccountNumber': json['to_account_number'] == null ? undefined : json['to_account_number'],
        'toAccountRoutingNumber': json['to_account_routing_number'] == null ? undefined : json['to_account_routing_number'],
        'toAccountInstitutionName': json['to_account_institution_name'] == null ? undefined : json['to_account_institution_name'],
        'beneficiaryName': json['beneficiary_name'] == null ? undefined : json['beneficiary_name'],
        'beneficiaryAddress1': json['beneficiary_address_1'] == null ? undefined : json['beneficiary_address_1'],
        'beneficiaryAddress2': json['beneficiary_address_2'] == null ? undefined : json['beneficiary_address_2'],
        'beneficiaryAddress3': json['beneficiary_address_3'] == null ? undefined : json['beneficiary_address_3'],
        'memo1': json['memo_1'] == null ? undefined : json['memo_1'],
        'memo2': json['memo_2'] == null ? undefined : json['memo_2'],
        'memo3': json['memo_3'] == null ? undefined : json['memo_3'],
        'memo4': json['memo_4'] == null ? undefined : json['memo_4'],
        'state': json['state'] == null ? undefined : json['state'],
        'displayState': json['display_state'] == null ? undefined : json['display_state'],
        'templateName': json['template_name'] == null ? undefined : json['template_name'],
        'wireReason': json['wire_reason'] == null ? undefined : json['wire_reason'],
    };
}

export function WireToJSON(value?: Omit<Wire, 'id'|'created_at'|'processed_at'|'amount'|'from_account'|'from_account_display'|'to_account_number'|'to_account_routing_number'|'to_account_institution_name'|'beneficiary_name'|'beneficiary_address_1'|'beneficiary_address_2'|'beneficiary_address_3'|'memo_1'|'memo_2'|'memo_3'|'memo_4'|'state'|'display_state'|'template_name'|'wire_reason'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

