/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.7.99)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WireImportSubmitRowRequest } from './WireImportSubmitRowRequest';
import {
    WireImportSubmitRowRequestFromJSON,
    WireImportSubmitRowRequestFromJSONTyped,
    WireImportSubmitRowRequestToJSON,
} from './WireImportSubmitRowRequest';

/**
 * 
 * @export
 * @interface WireImportSubmitRequest
 */
export interface WireImportSubmitRequest {
    /**
     * 
     * @type {string}
     * @memberof WireImportSubmitRequest
     */
    s3Key: string;
    /**
     * 
     * @type {string}
     * @memberof WireImportSubmitRequest
     */
    fromAccount: string;
    /**
     * 
     * @type {string}
     * @memberof WireImportSubmitRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof WireImportSubmitRequest
     */
    note?: string | null;
    /**
     * 
     * @type {Array<WireImportSubmitRowRequest>}
     * @memberof WireImportSubmitRequest
     */
    rows: Array<WireImportSubmitRowRequest>;
}

/**
 * Check if a given object implements the WireImportSubmitRequest interface.
 */
export function instanceOfWireImportSubmitRequest(value: object): value is WireImportSubmitRequest {
    if (!('s3Key' in value) || value['s3Key'] === undefined) return false;
    if (!('fromAccount' in value) || value['fromAccount'] === undefined) return false;
    if (!('rows' in value) || value['rows'] === undefined) return false;
    return true;
}

export function WireImportSubmitRequestFromJSON(json: any): WireImportSubmitRequest {
    return WireImportSubmitRequestFromJSONTyped(json, false);
}

export function WireImportSubmitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WireImportSubmitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        's3Key': json['s3_key'],
        'fromAccount': json['from_account'],
        'description': json['description'] == null ? undefined : json['description'],
        'note': json['note'] == null ? undefined : json['note'],
        'rows': ((json['rows'] as Array<any>).map(WireImportSubmitRowRequestFromJSON)),
    };
}

export function WireImportSubmitRequestToJSON(value?: WireImportSubmitRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        's3_key': value['s3Key'],
        'from_account': value['fromAccount'],
        'description': value['description'],
        'note': value['note'],
        'rows': ((value['rows'] as Array<any>).map(WireImportSubmitRowRequestToJSON)),
    };
}

