/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.3.79)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Wire } from './Wire';
import {
    WireFromJSON,
    WireFromJSONTyped,
    WireToJSON,
} from './Wire';

/**
 * 
 * @export
 * @interface WireCreateResponse
 */
export interface WireCreateResponse {
    /**
     * 
     * @type {Array<Wire>}
     * @memberof WireCreateResponse
     */
    wires: Array<Wire>;
}

/**
 * Check if a given object implements the WireCreateResponse interface.
 */
export function instanceOfWireCreateResponse(value: object): value is WireCreateResponse {
    if (!('wires' in value) || value['wires'] === undefined) return false;
    return true;
}

export function WireCreateResponseFromJSON(json: any): WireCreateResponse {
    return WireCreateResponseFromJSONTyped(json, false);
}

export function WireCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WireCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'wires': ((json['wires'] as Array<any>).map(WireFromJSON)),
    };
}

export function WireCreateResponseToJSON(value?: WireCreateResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'wires': ((value['wires'] as Array<any>).map(WireToJSON)),
    };
}

