/* tslint:disable */
/* eslint-disable */
/**
 * Narmi Public API
 * To read about Public API access and authentication, go to [API Overview](https://docs.narmi.com/docs/narmi-developer-docs/xl9dvbz84o11l-introduction).
 *
 * The version of the OpenAPI document: v1 (v2026.6.31)
 * Contact: support@narmi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WireCSVFieldMapping
 */
export interface WireCSVFieldMapping {
    /**
     * 
     * @type {string}
     * @memberof WireCSVFieldMapping
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof WireCSVFieldMapping
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WireCSVFieldMapping
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof WireCSVFieldMapping
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof WireCSVFieldMapping
     */
    hasHeaderRow?: boolean;
    /**
     * 
     * @type {number}
     * @memberof WireCSVFieldMapping
     */
    recipientNameColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WireCSVFieldMapping
     */
    recipientNameColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WireCSVFieldMapping
     */
    routingNumberColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WireCSVFieldMapping
     */
    routingNumberColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WireCSVFieldMapping
     */
    accountNumberColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WireCSVFieldMapping
     */
    accountNumberColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WireCSVFieldMapping
     */
    amountColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WireCSVFieldMapping
     */
    amountColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WireCSVFieldMapping
     */
    memoColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WireCSVFieldMapping
     */
    memoColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WireCSVFieldMapping
     */
    wireReasonColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WireCSVFieldMapping
     */
    wireReasonColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WireCSVFieldMapping
     */
    recipientStreetAddressColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WireCSVFieldMapping
     */
    recipientStreetAddressColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WireCSVFieldMapping
     */
    recipientCityColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WireCSVFieldMapping
     */
    recipientCityColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WireCSVFieldMapping
     */
    recipientRegionCodeColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WireCSVFieldMapping
     */
    recipientRegionCodeColumnHeader?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WireCSVFieldMapping
     */
    recipientPostalCodeColumnIndex?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WireCSVFieldMapping
     */
    recipientPostalCodeColumnHeader?: string | null;
}

/**
 * Check if a given object implements the WireCSVFieldMapping interface.
 */
export function instanceOfWireCSVFieldMapping(value: object): value is WireCSVFieldMapping {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function WireCSVFieldMappingFromJSON(json: any): WireCSVFieldMapping {
    return WireCSVFieldMappingFromJSONTyped(json, false);
}

export function WireCSVFieldMappingFromJSONTyped(json: any, ignoreDiscriminator: boolean): WireCSVFieldMapping {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'name': json['name'],
        'hasHeaderRow': json['has_header_row'] == null ? undefined : json['has_header_row'],
        'recipientNameColumnIndex': json['recipient_name_column_index'] == null ? undefined : json['recipient_name_column_index'],
        'recipientNameColumnHeader': json['recipient_name_column_header'] == null ? undefined : json['recipient_name_column_header'],
        'routingNumberColumnIndex': json['routing_number_column_index'] == null ? undefined : json['routing_number_column_index'],
        'routingNumberColumnHeader': json['routing_number_column_header'] == null ? undefined : json['routing_number_column_header'],
        'accountNumberColumnIndex': json['account_number_column_index'] == null ? undefined : json['account_number_column_index'],
        'accountNumberColumnHeader': json['account_number_column_header'] == null ? undefined : json['account_number_column_header'],
        'amountColumnIndex': json['amount_column_index'] == null ? undefined : json['amount_column_index'],
        'amountColumnHeader': json['amount_column_header'] == null ? undefined : json['amount_column_header'],
        'memoColumnIndex': json['memo_column_index'] == null ? undefined : json['memo_column_index'],
        'memoColumnHeader': json['memo_column_header'] == null ? undefined : json['memo_column_header'],
        'wireReasonColumnIndex': json['wire_reason_column_index'] == null ? undefined : json['wire_reason_column_index'],
        'wireReasonColumnHeader': json['wire_reason_column_header'] == null ? undefined : json['wire_reason_column_header'],
        'recipientStreetAddressColumnIndex': json['recipient_street_address_column_index'] == null ? undefined : json['recipient_street_address_column_index'],
        'recipientStreetAddressColumnHeader': json['recipient_street_address_column_header'] == null ? undefined : json['recipient_street_address_column_header'],
        'recipientCityColumnIndex': json['recipient_city_column_index'] == null ? undefined : json['recipient_city_column_index'],
        'recipientCityColumnHeader': json['recipient_city_column_header'] == null ? undefined : json['recipient_city_column_header'],
        'recipientRegionCodeColumnIndex': json['recipient_region_code_column_index'] == null ? undefined : json['recipient_region_code_column_index'],
        'recipientRegionCodeColumnHeader': json['recipient_region_code_column_header'] == null ? undefined : json['recipient_region_code_column_header'],
        'recipientPostalCodeColumnIndex': json['recipient_postal_code_column_index'] == null ? undefined : json['recipient_postal_code_column_index'],
        'recipientPostalCodeColumnHeader': json['recipient_postal_code_column_header'] == null ? undefined : json['recipient_postal_code_column_header'],
    };
}

export function WireCSVFieldMappingToJSON(value?: Omit<WireCSVFieldMapping, 'id'|'created_at'|'updated_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'has_header_row': value['hasHeaderRow'],
        'recipient_name_column_index': value['recipientNameColumnIndex'],
        'recipient_name_column_header': value['recipientNameColumnHeader'],
        'routing_number_column_index': value['routingNumberColumnIndex'],
        'routing_number_column_header': value['routingNumberColumnHeader'],
        'account_number_column_index': value['accountNumberColumnIndex'],
        'account_number_column_header': value['accountNumberColumnHeader'],
        'amount_column_index': value['amountColumnIndex'],
        'amount_column_header': value['amountColumnHeader'],
        'memo_column_index': value['memoColumnIndex'],
        'memo_column_header': value['memoColumnHeader'],
        'wire_reason_column_index': value['wireReasonColumnIndex'],
        'wire_reason_column_header': value['wireReasonColumnHeader'],
        'recipient_street_address_column_index': value['recipientStreetAddressColumnIndex'],
        'recipient_street_address_column_header': value['recipientStreetAddressColumnHeader'],
        'recipient_city_column_index': value['recipientCityColumnIndex'],
        'recipient_city_column_header': value['recipientCityColumnHeader'],
        'recipient_region_code_column_index': value['recipientRegionCodeColumnIndex'],
        'recipient_region_code_column_header': value['recipientRegionCodeColumnHeader'],
        'recipient_postal_code_column_index': value['recipientPostalCodeColumnIndex'],
        'recipient_postal_code_column_header': value['recipientPostalCodeColumnHeader'],
    };
}

