name: Scan Secrets
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "* 6 * * *" # every day at 6am server time

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        name: Check for secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
      - name: Send alert
        if: github.event_name == 'schedule' && success()
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          server_port: 465 # or 587 for TLS
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          to: recipient@example.com
          from: "SDK Email Bot  <notifications@narmi.com>"
          subject: "Success: TypeScript SDK Scan Results"
          body: "This email was triggered via the secrets scanning workflow @ https://github.com/narmi/public-api-sdk-ts/actions/workflows/secrets.yml."
      - name: Send alert
        if: github.event_name == 'schedule' && failure()
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          server_port: 465 # or 587 for TLS
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          to: recipient@example.com
          from: "SDK Email Bot  <notifications@narmi.com>"
          subject: "FAILURE: TypeScript SDK Scan Results"
          body: "Check for failures in the task https://github.com/narmi/public-api-sdk-ts/actions/workflows/secrets.yml."
